// Language context for multi-language support
import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es' | 'ht';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.grenadiers': 'Les Grenadiers',
    // Grenadiers
    'gren.subtitle': 'Haiti National Team',
    'gren.back': 'Home',
    'gren.players': 'players',
    'gren.statLines': 'stat lines',
    'gren.callupsWord': 'call-ups',
    'gren.tabSquad': 'Squad',
    'gren.tabStats': 'Statistics',
    'gren.tabCallups': 'Call-ups',
    'gren.posGk': 'Goalkeepers',
    'gren.posDef': 'Defenders',
    'gren.posMid': 'Midfielders',
    'gren.posAtt': 'Forwards',
    'gren.posOther': 'Others',
    'gren.currentClub': 'Current club',
    'gren.clubCountry': 'Club country',
    'gren.birth': 'Birth',
    'gren.birthPlace': 'Birthplace',
    'gren.marketValue': 'Market value',
    'gren.status': 'Status',
    'gren.contract': 'Contract',
    'gren.agent': 'Agent',
    'gren.injuries': 'Recent injuries',
    'gren.career': 'Career',
    'gren.years': 'yrs',
    'gren.merchPerso': 'Personal merch',
    'gren.merchClub': 'Club merch',
    'gren.statsTitle': 'Statistics',
    'gren.callupsTitle': 'Call-ups',
    'gren.thPlayer': 'Player',
    'gren.thSeason': 'Season',
    'gren.thCompetition': 'Competition',
    'gren.thClub': 'Club/Sel.',
    'gren.thMp': 'MP',
    'gren.thStarts': 'Starts',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Goals',
    'gren.thAssists': 'A',
    'gren.thYellow': 'YC',
    'gren.thRed': 'RC',
    'gren.thRating': 'Rating',
    'gren.thTournament': 'Tournament',
    'gren.thDate': 'Date',
    'gren.thOpponent': 'Opponent',
    'gren.thLocation': 'Venue',
    'gren.thResult': 'Result',
    'gren.thPresence': 'Presence',
    'gren.tournament': 'Tournament',
    'gren.allTournaments': 'All tournaments',
    'gren.matches': 'match(es)',
    'gren.noStats': 'No statistics available.',
    'gren.noCallups': 'No call-ups available.',
    'gren.present': 'Present',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Articles',
    'nav.askMenlifoot': 'Ask Menlifoot',
    'nav.store': 'Store',
    'nav.signIn': 'Sign In',
    'nav.login': 'Login',
    'nav.logout': 'Sign Out',
    'nav.editorial': 'Editorial',
    
    // Profile
    'profile.settings': 'Profile Settings',
    'profile.profile': 'Profile',
    'profile.security': 'Security',
    'profile.avatarHint': 'Click to change avatar',
    'profile.displayName': 'Display Name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.email': 'Email',
    'profile.save': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.updatePassword': 'Update Password',
    'profile.removeAvatar': 'Remove',
    'profile.avatarRemoved': 'Avatar removed successfully',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'New Episode Available',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Dive deep into the beautiful game with expert analysis, player interviews, and match breakdowns from the world\'s biggest leagues.',
    'hero.listenNow': 'Listen Now',
    'hero.browseEpisodes': 'Browse Episodes',
    'hero.episodeTitle': 'World Cup 2026 Preview',
    'hero.episodeInfo': 'Episode 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Live Updates',
    'news.title': 'Latest',
    'news.titleHighlight': 'News',
    'news.description': 'Stay updated with the latest soccer news from around the world',
    'news.worldCup': 'World Cup 2026',
    'news.roadTo2026': 'The Road to 2026',
    'news.wcDescription': 'Everything you need to know about the upcoming FIFA World Cup hosted across USA, Mexico, and Canada.',
    'news.exploreCoverage': 'Explore Coverage',
    'news.latestQualifier': 'Latest Qualifier Results',
    'news.latestUpdates': 'Latest Updates',
    'news.viewAll': 'View All News',
    'news.backToNews': 'Back to News',
    'news.backToHome': 'Back to Home',
    'news.footballNews': 'Football',
    'news.newsTitle': 'News',
    'news.newsDescription': 'Your source for the latest football news, transfers, and match updates',
    'news.allNews': 'All News',
    'news.transfers': 'Transfers',
    'news.championsLeague': 'Champions League',
    'news.matches': 'Matches',
    'news.injuries': 'Injuries',
    'news.noNews': 'No news available',
    'news.checkBack': 'Check back later for updates',
    'news.searchPlaceholder': 'Search news...',
    'news.source': 'Source',
    'news.by': 'By',
    'news.readFull': 'Read Full Article',
    
    // Merch Section
    'merch.exclusive': 'Exclusive Drops',
    'merch.title': 'Official',
    'merch.titleHighlight': 'Merch',
    'merch.description': 'Rep your passion with premium Menlifoot gear. Limited edition drops you won\'t find anywhere else.',
    'merch.shopNow': 'Shop Now',
    'merch.addToCart': 'Add to Cart',
    'merch.added': 'Added to cart',
    
    // Social Section
    'social.community': 'Join the Community',
    'social.title': 'Connect',
    'social.titleHighlight': 'With Us',
    'social.description': 'Follow our journey across platforms and become part of the Menlifoot family.',
    'social.followers': 'followers',
    'social.subscribers': 'subscribers',
    
    // AI Agent
    'ai.title': 'Menlifoot Expert',
    'ai.subtitle': 'Powered by Prof Menlifoot',
    'ai.placeholder': 'Ask me anything about soccer...',
    'ai.greeting': 'Hey! I\'m your Menlifoot Expert. Got questions about match predictions, player stats, transfer news, or World Cup 2026? Let\'s talk football.',
    
    // Chat Section
    'chat.poweredBy': 'Powered by Prof Menlifoot',
    'chat.askThe': 'Ask the',
    'chat.expertName': 'Menlifoot Expert',
    'chat.description': 'Get instant answers about match predictions, player stats, transfer news, tactics, and everything football.',
    'chat.alwaysReady': 'Always ready to help',
    'chat.tryAsking': 'Try asking:',
    
    // Footer
    'footer.tagline': 'Your ultimate soccer companion. Stay connected with the beautiful game through podcasts, news, and community.',
    'footer.company': 'Company',
    'footer.content': 'Content',
    'footer.support': 'Support',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.contact': 'Contact',
    'footer.podcast': 'Podcast',
    'footer.news': 'News',
    'footer.videos': 'Videos',
    'footer.newsletter': 'Newsletter',
    'footer.helpCenter': 'Help Center',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.editorial': 'Editorial',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.rights': 'All rights reserved.',
    
    // Splash
    'splash.companion': 'Your Soccer Companion',
    
    // Articles
    'articles.badge': 'Latest Articles',
    'articles.title': 'Featured',
    'articles.titleHighlight': 'Articles',
    'articles.description': 'Expert insights, analysis, and stories from the world of football.',
    'articles.save': 'Save',
    'articles.share': 'Share',
    'articles.saved': 'Saved',
    'articles.removed': 'Removed',
    'articles.addedToSaved': 'Article added to saved',
    'articles.removedFromSaved': 'Article removed from saved',
    'articles.copied': 'Copied',
    'articles.linkCopied': 'Link copied to clipboard',
    'articles.keywords': 'Keywords',
    'articles.shared': 'Shared',
    'articles.sharedSuccess': 'Article shared successfully',
    'articles.shareError': 'Share failed',
    'articles.shareErrorDesc': 'Could not share the article',
    'articles.translating': 'Translating...',
    'articles.filters': 'Filters',
    'articles.clearAll': 'Clear all',
    'articles.latest': 'Latest',
    'articles.oldest': 'Oldest',
    'articles.popular': 'Popular',
    'articles.latestFirst': 'Latest First',
    'articles.oldestFirst': 'Oldest First',
    'articles.mostPopular': 'Most Popular',
    'articles.category': 'Category',
    'articles.author': 'Author',
    'articles.showingOf': 'Showing {count} of {total} articles',
    'articles.all': 'All',
    'articles.cat.matchAnalysis': 'Match Analysis',
    'articles.cat.transferNews': 'Transfer News',
    'articles.cat.playerSpotlight': 'Player Spotlight',
    'articles.cat.worldCup2026': 'World Cup 2026',
    'articles.cat.championsLeague': 'Champions League',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Tactics',
    'articles.cat.opinion': 'Opinion',
    'articles.cat.didYouKnow': 'Did You Know?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Football Business',
    'articles.cat.haiti': 'Haiti',
    'articles.subtitle': 'The latest football news, transfers, and analysis from around the world',
    'articles.searchPlaceholder': 'Search articles...',
    'articles.noResults': 'No articles found',
    'articles.tryDifferentSearch': 'Try a different search term or category',
    'articles.moreStories': 'More Stories',
    'articles.backToArticles': 'Back to Articles',
    'articles.notFound': 'Article not found',
    'articles.views': 'views',
    'articles.likes': 'Likes',
    'articles.similarArticles': 'Similar Articles',
    'articles.loginToLike': 'Login required',
    'articles.loginToLikeDesc': 'Please login to like articles',
    'articles.shareSuccess': 'Article link copied to clipboard',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Test your football knowledge with timed trivia challenges',
    'quiz.noQuizzes': 'No quizzes available yet',
    'quiz.play': 'Play',
    'quiz.startQuiz': 'Start Quiz',
    'quiz.loading': 'Loading...',
    'quiz.notFound': 'Quiz not found',
    'quiz.browseQuizzes': 'Browse Quizzes',
    'quiz.minutes': 'minutes',
    'quiz.answers': 'answers',
    'quiz.answer': 'Answer',
    'quiz.value': 'Value',
    'quiz.typeAnswer': 'Type your answer...',
    'quiz.giveUp': 'Give Up',
    'quiz.hint': 'Hint',
    'quiz.loginForHint': 'Login required',
    'quiz.loginForHintDesc': 'Create an account to unlock hints',
    'quiz.results': 'Results',
    'quiz.timeTaken': 'Time',
    'quiz.playAgain': 'Play Again',
    'quiz.share': 'Share',
    'quiz.shareScore': 'Share Score',
    'quiz.shareChallenge': 'Can you beat my score?',
    'quiz.linkCopied': 'Link copied!',

    // Common
    'common.back': 'Back',
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.grenadiers': 'Les Grenadiers',
    // Grenadiers
    'gren.subtitle': 'Sélection nationale d\'Haïti',
    'gren.back': 'Accueil',
    'gren.players': 'joueurs',
    'gren.statLines': 'lignes de stats',
    'gren.callupsWord': 'convocations',
    'gren.tabSquad': 'Effectif',
    'gren.tabStats': 'Statistiques',
    'gren.tabCallups': 'Convocations',
    'gren.posGk': 'Gardiens',
    'gren.posDef': 'Défenseurs',
    'gren.posMid': 'Milieux',
    'gren.posAtt': 'Attaquants',
    'gren.posOther': 'Autres',
    'gren.currentClub': 'Club actuel',
    'gren.clubCountry': 'Pays du club',
    'gren.birth': 'Naissance',
    'gren.birthPlace': 'Lieu de naissance',
    'gren.marketValue': 'Valeur marchande',
    'gren.status': 'Statut',
    'gren.contract': 'Contrat',
    'gren.agent': 'Agent',
    'gren.injuries': 'Blessures récentes',
    'gren.career': 'Parcours',
    'gren.years': 'ans',
    'gren.merchPerso': 'Merch perso',
    'gren.merchClub': 'Merch club',
    'gren.statsTitle': 'Statistiques',
    'gren.callupsTitle': 'Convocations',
    'gren.thPlayer': 'Joueur',
    'gren.thSeason': 'Saison',
    'gren.thCompetition': 'Compétition',
    'gren.thClub': 'Club/Sél.',
    'gren.thMp': 'MJ',
    'gren.thStarts': 'Titu',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Buts',
    'gren.thAssists': 'PD',
    'gren.thYellow': 'CJ',
    'gren.thRed': 'CR',
    'gren.thRating': 'Note',
    'gren.thTournament': 'Tournoi',
    'gren.thDate': 'Date',
    'gren.thOpponent': 'Adversaire',
    'gren.thLocation': 'Lieu',
    'gren.thResult': 'Résultat',
    'gren.thPresence': 'Présence',
    'gren.tournament': 'Tournoi',
    'gren.allTournaments': 'Tous les tournois',
    'gren.matches': 'match(s)',
    'gren.noStats': 'Aucune statistique disponible.',
    'gren.noCallups': 'Aucune convocation disponible.',
    'gren.present': 'Présent',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Articles',
    'nav.askMenlifoot': 'Demander Menlifoot',
    'nav.store': 'Boutique',
    'nav.signIn': 'Connexion',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.editorial': 'Éditorial',
    
    // Profile
    'profile.settings': 'Paramètres du profil',
    'profile.profile': 'Profil',
    'profile.security': 'Sécurité',
    'profile.avatarHint': 'Cliquez pour changer l\'avatar',
    'profile.displayName': 'Nom d\'affichage',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Parlez-nous de vous...',
    'profile.email': 'Email',
    'profile.save': 'Enregistrer',
    'profile.changePassword': 'Changer le mot de passe',
    'profile.currentPassword': 'Mot de passe actuel',
    'profile.newPassword': 'Nouveau mot de passe',
    'profile.confirmPassword': 'Confirmer le mot de passe',
    'profile.updatePassword': 'Mettre à jour le mot de passe',
    'profile.removeAvatar': 'Supprimer',
    'profile.avatarRemoved': 'Avatar supprimé avec succès',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'Nouvel Épisode Disponible',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Plongez dans le beau jeu avec des analyses d\'experts, des interviews de joueurs et des analyses de matchs des plus grandes ligues du monde.',
    'hero.listenNow': 'Écouter',
    'hero.browseEpisodes': 'Parcourir les Épisodes',
    'hero.episodeTitle': 'Aperçu Coupe du Monde 2026',
    'hero.episodeInfo': 'Épisode 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Mises à Jour en Direct',
    'news.title': 'Dernières',
    'news.titleHighlight': 'Actualités',
    'news.description': 'Restez informé des dernières actualités du football mondial',
    'news.worldCup': 'Coupe du Monde 2026',
    'news.roadTo2026': 'La Route vers 2026',
    'news.wcDescription': 'Tout ce que vous devez savoir sur la prochaine Coupe du Monde FIFA organisée aux États-Unis, au Mexique et au Canada.',
    'news.exploreCoverage': 'Explorer la Couverture',
    'news.latestQualifier': 'Derniers Résultats des Qualifications',
    'news.latestUpdates': 'Dernières Mises à Jour',
    'news.viewAll': 'Voir Toutes les Actualités',
    'news.backToNews': 'Retour aux Actualités',
    'news.backToHome': 'Retour à l\'Accueil',
    'news.footballNews': 'Football',
    'news.newsTitle': 'Actualités',
    'news.newsDescription': 'Votre source pour les dernières actualités, transferts et résultats de football',
    'news.allNews': 'Toutes les Actualités',
    'news.transfers': 'Transferts',
    'news.championsLeague': 'Ligue des Champions',
    'news.matches': 'Matchs',
    'news.injuries': 'Blessures',
    'news.noNews': 'Aucune actualité disponible',
    'news.checkBack': 'Revenez plus tard pour les mises à jour',
    'news.searchPlaceholder': 'Rechercher des nouvelles...',
    'news.source': 'Source',
    'news.by': 'Par',
    'news.readFull': 'Lire l\'Article Complet',
    
    // Merch Section
    'merch.exclusive': 'Collections Exclusives',
    'merch.title': 'Boutique',
    'merch.titleHighlight': 'Officielle',
    'merch.description': 'Montrez votre passion avec des articles Menlifoot premium. Éditions limitées introuvables ailleurs.',
    'merch.shopNow': 'Acheter',
    'merch.addToCart': 'Ajouter au Panier',
    'merch.added': 'Ajouté au panier',
    
    // Social Section
    'social.community': 'Rejoignez la Communauté',
    'social.title': 'Connectez',
    'social.titleHighlight': '-vous',
    'social.description': 'Suivez notre parcours sur toutes les plateformes et faites partie de la famille Menlifoot.',
    'social.followers': 'abonnés',
    'social.subscribers': 'abonnés',
    
    // AI Agent
    'ai.title': 'Expert Menlifoot',
    'ai.subtitle': 'Propulsé par Prof Menlifoot',
    'ai.placeholder': 'Posez-moi une question sur le football...',
    'ai.greeting': 'Salut! Je suis votre Expert Menlifoot. Des questions sur les prédictions de matchs, les stats des joueurs, les nouvelles de transferts ou la Coupe du Monde 2026? Parlons football.',
    
    // Chat Section
    'chat.poweredBy': 'Propulsé par Prof Menlifoot',
    'chat.askThe': 'Demandez à',
    'chat.expertName': 'l\'Expert Menlifoot',
    'chat.description': 'Obtenez des réponses instantanées sur les prédictions de matchs, statistiques de joueurs, actualités transferts et tout le football.',
    'chat.alwaysReady': 'Toujours prêt à aider',
    'chat.tryAsking': 'Essayez de demander:',
    
    // Footer
    'footer.tagline': 'Votre compagnon football ultime. Restez connecté au beau jeu grâce aux podcasts, actualités et communauté.',
    'footer.company': 'Entreprise',
    'footer.content': 'Contenu',
    'footer.support': 'Support',
    'footer.aboutUs': 'À Propos',
    'footer.careers': 'Carrières',
    'footer.press': 'Presse',
    'footer.contact': 'Contact',
    'footer.podcast': 'Podcast',
    'footer.news': 'Actualités',
    'footer.videos': 'Vidéos',
    'footer.newsletter': 'Newsletter',
    'footer.helpCenter': 'Centre d\'Aide',
    'footer.privacyPolicy': 'Politique de Confidentialité',
    'footer.termsOfService': 'Conditions d\'Utilisation',
    'footer.cookiePolicy': 'Politique des Cookies',
    'footer.editorial': 'Éditorial',
    'footer.emailPlaceholder': 'Entrez votre email',
    'footer.rights': 'Tous droits réservés.',
    
    // Splash
    'splash.companion': 'Votre Compagnon Football',
    
    // Articles
    'articles.badge': 'Derniers Articles',
    'articles.title': 'Articles',
    'articles.titleHighlight': 'Vedettes',
    'articles.description': 'Analyses expertes, insights et histoires du monde du football.',
    'articles.save': 'Sauvegarder',
    'articles.share': 'Partager',
    'articles.saved': 'Sauvegardé',
    'articles.removed': 'Supprimé',
    'articles.addedToSaved': 'Article ajouté aux favoris',
    'articles.removedFromSaved': 'Article retiré des favoris',
    'articles.copied': 'Copié',
    'articles.linkCopied': 'Lien copié dans le presse-papiers',
    'articles.keywords': 'Mots-clés',
    'articles.shared': 'Partagé',
    'articles.sharedSuccess': 'Article partagé avec succès',
    'articles.shareError': 'Échec du partage',
    'articles.shareErrorDesc': 'Impossible de partager l\'article',
    'articles.translating': 'Traduction en cours...',
    'articles.filters': 'Filtres',
    'articles.clearAll': 'Tout effacer',
    'articles.latest': 'Récent',
    'articles.oldest': 'Ancien',
    'articles.popular': 'Populaire',
    'articles.latestFirst': 'Plus récent',
    'articles.oldestFirst': 'Plus ancien',
    'articles.mostPopular': 'Plus populaire',
    'articles.category': 'Catégorie',
    'articles.author': 'Auteur',
    'articles.showingOf': 'Affichage de {count} sur {total} articles',
    'articles.all': 'Tous',
    'articles.cat.matchAnalysis': 'Analyse de match',
    'articles.cat.transferNews': 'Actualités transferts',
    'articles.cat.playerSpotlight': 'Joueur à l\'honneur',
    'articles.cat.worldCup2026': 'Coupe du Monde 2026',
    'articles.cat.championsLeague': 'Ligue des Champions',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Tactiques',
    'articles.cat.opinion': 'Opinion',
    'articles.cat.didYouKnow': 'Le saviez-vous ?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Business du Football',
    'articles.cat.haiti': 'Haïti',
    'articles.subtitle': 'Les dernières actualités, transferts et analyses du football du monde entier',
    'articles.searchPlaceholder': 'Rechercher des articles...',
    'articles.noResults': 'Aucun article trouvé',
    'articles.tryDifferentSearch': 'Essayez un autre terme ou catégorie',
    'articles.moreStories': 'Plus d\'histoires',
    'articles.backToArticles': 'Retour aux articles',
    'articles.notFound': 'Article non trouvé',
    'articles.views': 'vues',
    'articles.likes': 'J\'aime',
    'articles.similarArticles': 'Articles similaires',
    'articles.loginToLike': 'Connexion requise',
    'articles.loginToLikeDesc': 'Veuillez vous connecter pour aimer les articles',
    'articles.shareSuccess': 'Lien de l\'article copié',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Testez vos connaissances en football avec des défis chronométrés',
    'quiz.noQuizzes': 'Pas encore de quiz disponible',
    'quiz.play': 'Jouer',
    'quiz.startQuiz': 'Commencer le Quiz',
    'quiz.loading': 'Chargement...',
    'quiz.notFound': 'Quiz introuvable',
    'quiz.browseQuizzes': 'Parcourir les Quiz',
    'quiz.minutes': 'minutes',
    'quiz.answers': 'réponses',
    'quiz.answer': 'Réponse',
    'quiz.value': 'Valeur',
    'quiz.typeAnswer': 'Tapez votre réponse...',
    'quiz.giveUp': 'Abandonner',
    'quiz.hint': 'Indice',
    'quiz.loginForHint': 'Connexion requise',
    'quiz.loginForHintDesc': 'Créez un compte pour débloquer les indices',
    'quiz.results': 'Résultats',
    'quiz.timeTaken': 'Temps',
    'quiz.playAgain': 'Rejouer',
    'quiz.share': 'Partager',
    'quiz.shareScore': 'Partager le score',
    'quiz.shareChallenge': 'Tu peux battre mon score ?',
    'quiz.linkCopied': 'Lien copié !',

    // Common
    'common.back': 'Retour',
  },
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.grenadiers': 'Les Grenadiers',
    // Grenadiers
    'gren.subtitle': 'Selección nacional de Haití',
    'gren.back': 'Inicio',
    'gren.players': 'jugadores',
    'gren.statLines': 'líneas de estadísticas',
    'gren.callupsWord': 'convocatorias',
    'gren.tabSquad': 'Plantilla',
    'gren.tabStats': 'Estadísticas',
    'gren.tabCallups': 'Convocatorias',
    'gren.posGk': 'Porteros',
    'gren.posDef': 'Defensas',
    'gren.posMid': 'Centrocampistas',
    'gren.posAtt': 'Delanteros',
    'gren.posOther': 'Otros',
    'gren.currentClub': 'Club actual',
    'gren.clubCountry': 'País del club',
    'gren.birth': 'Nacimiento',
    'gren.birthPlace': 'Lugar de nacimiento',
    'gren.marketValue': 'Valor de mercado',
    'gren.status': 'Estado',
    'gren.contract': 'Contrato',
    'gren.agent': 'Agente',
    'gren.injuries': 'Lesiones recientes',
    'gren.career': 'Trayectoria',
    'gren.years': 'años',
    'gren.merchPerso': 'Merch personal',
    'gren.merchClub': 'Merch del club',
    'gren.statsTitle': 'Estadísticas',
    'gren.callupsTitle': 'Convocatorias',
    'gren.thPlayer': 'Jugador',
    'gren.thSeason': 'Temporada',
    'gren.thCompetition': 'Competición',
    'gren.thClub': 'Club/Sel.',
    'gren.thMp': 'PJ',
    'gren.thStarts': 'Tit',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Goles',
    'gren.thAssists': 'A',
    'gren.thYellow': 'TA',
    'gren.thRed': 'TR',
    'gren.thRating': 'Nota',
    'gren.thTournament': 'Torneo',
    'gren.thDate': 'Fecha',
    'gren.thOpponent': 'Rival',
    'gren.thLocation': 'Lugar',
    'gren.thResult': 'Resultado',
    'gren.thPresence': 'Presencia',
    'gren.tournament': 'Torneo',
    'gren.allTournaments': 'Todos los torneos',
    'gren.matches': 'partido(s)',
    'gren.noStats': 'No hay estadísticas disponibles.',
    'gren.noCallups': 'No hay convocatorias disponibles.',
    'gren.present': 'Presente',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Artículos',
    'nav.askMenlifoot': 'Preguntar Menlifoot',
    'nav.store': 'Tienda',
    'nav.signIn': 'Iniciar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.editorial': 'Editorial',
    
    // Profile
    'profile.settings': 'Configuración del Perfil',
    'profile.profile': 'Perfil',
    'profile.security': 'Seguridad',
    'profile.avatarHint': 'Haz clic para cambiar el avatar',
    'profile.displayName': 'Nombre',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Cuéntanos sobre ti...',
    'profile.email': 'Correo electrónico',
    'profile.save': 'Guardar Cambios',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.currentPassword': 'Contraseña Actual',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.confirmPassword': 'Confirmar Contraseña',
    'profile.updatePassword': 'Actualizar Contraseña',
    'profile.removeAvatar': 'Eliminar',
    'profile.avatarRemoved': 'Avatar eliminado con éxito',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'Nuevo Episodio Disponible',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Sumérgete en el hermoso juego con análisis de expertos, entrevistas a jugadores y resúmenes de partidos de las ligas más grandes del mundo.',
    'hero.listenNow': 'Escuchar',
    'hero.browseEpisodes': 'Ver Episodios',
    'hero.episodeTitle': 'Adelanto Copa del Mundo 2026',
    'hero.episodeInfo': 'Episodio 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Actualizaciones en Vivo',
    'news.title': 'Últimas',
    'news.titleHighlight': 'Noticias',
    'news.description': 'Mantente actualizado con las últimas noticias del fútbol mundial',
    'news.worldCup': 'Copa del Mundo 2026',
    'news.roadTo2026': 'El Camino a 2026',
    'news.wcDescription': 'Todo lo que necesitas saber sobre la próxima Copa del Mundo FIFA en Estados Unidos, México y Canadá.',
    'news.exploreCoverage': 'Explorar Cobertura',
    'news.latestQualifier': 'Últimos Resultados de Clasificación',
    'news.latestUpdates': 'Últimas Actualizaciones',
    'news.viewAll': 'Ver Todas las Noticias',
    'news.backToNews': 'Volver a Noticias',
    'news.backToHome': 'Volver al Inicio',
    'news.footballNews': 'Fútbol',
    'news.newsTitle': 'Noticias',
    'news.newsDescription': 'Tu fuente de las últimas noticias, fichajes y resultados de fútbol',
    'news.allNews': 'Todas las Noticias',
    'news.transfers': 'Fichajes',
    'news.championsLeague': 'Champions League',
    'news.matches': 'Partidos',
    'news.injuries': 'Lesiones',
    'news.noNews': 'No hay noticias disponibles',
    'news.checkBack': 'Vuelve más tarde para actualizaciones',
    'news.searchPlaceholder': 'Buscar noticias...',
    'news.source': 'Fuente',
    'news.by': 'Por',
    'news.readFull': 'Leer Artículo Completo',
    
    // Merch Section
    'merch.exclusive': 'Colecciones Exclusivas',
    'merch.title': 'Tienda',
    'merch.titleHighlight': 'Oficial',
    'merch.description': 'Muestra tu pasión con productos Menlifoot premium. Ediciones limitadas que no encontrarás en otro lugar.',
    'merch.shopNow': 'Comprar',
    'merch.addToCart': 'Añadir al Carrito',
    'merch.added': 'Añadido al carrito',
    
    // Social Section
    'social.community': 'Únete a la Comunidad',
    'social.title': 'Conéctate',
    'social.titleHighlight': 'Con Nosotros',
    'social.description': 'Sigue nuestro viaje en todas las plataformas y forma parte de la familia Menlifoot.',
    'social.followers': 'seguidores',
    'social.subscribers': 'suscriptores',
    
    // AI Agent
    'ai.title': 'Experto Menlifoot',
    'ai.subtitle': 'Impulsado por Prof Menlifoot',
    'ai.placeholder': 'Pregúntame cualquier cosa sobre fútbol...',
    'ai.greeting': '¡Hola! Soy tu Experto Menlifoot. ¿Tienes preguntas sobre predicciones, estadísticas de jugadores, noticias de fichajes o el Mundial 2026? Hablemos de fútbol.',
    
    // Chat Section
    'chat.poweredBy': 'Impulsado por Prof Menlifoot',
    'chat.askThe': 'Pregunta al',
    'chat.expertName': 'Experto Menlifoot',
    'chat.description': 'Obtén respuestas instantáneas sobre predicciones, estadísticas de jugadores, noticias de fichajes y todo sobre fútbol.',
    'chat.alwaysReady': 'Siempre listo para ayudar',
    'chat.tryAsking': 'Intenta preguntar:',
    
    // Footer
    'footer.tagline': 'Tu compañero definitivo de fútbol. Mantente conectado con el hermoso juego a través de podcasts, noticias y comunidad.',
    'footer.company': 'Empresa',
    'footer.content': 'Contenido',
    'footer.support': 'Soporte',
    'footer.aboutUs': 'Sobre Nosotros',
    'footer.careers': 'Carreras',
    'footer.press': 'Prensa',
    'footer.contact': 'Contacto',
    'footer.podcast': 'Podcast',
    'footer.news': 'Noticias',
    'footer.videos': 'Videos',
    'footer.newsletter': 'Boletín',
    'footer.helpCenter': 'Centro de Ayuda',
    'footer.privacyPolicy': 'Política de Privacidad',
    'footer.termsOfService': 'Términos de Servicio',
    'footer.cookiePolicy': 'Política de Cookies',
    'footer.editorial': 'Editorial',
    'footer.emailPlaceholder': 'Ingresa tu email',
    'footer.rights': 'Todos los derechos reservados.',
    
    // Splash
    'splash.companion': 'Tu Compañero de Fútbol',
    
    // Articles
    'articles.badge': 'Últimos Artículos',
    'articles.title': 'Artículos',
    'articles.titleHighlight': 'Destacados',
    'articles.description': 'Análisis expertos, perspectivas e historias del mundo del fútbol.',
    'articles.save': 'Guardar',
    'articles.share': 'Compartir',
    'articles.saved': 'Guardado',
    'articles.removed': 'Eliminado',
    'articles.addedToSaved': 'Artículo añadido a guardados',
    'articles.removedFromSaved': 'Artículo eliminado de guardados',
    'articles.copied': 'Copiado',
    'articles.linkCopied': 'Enlace copiado al portapapeles',
    'articles.keywords': 'Palabras clave',
    'articles.shared': 'Compartido',
    'articles.sharedSuccess': 'Artículo compartido con éxito',
    'articles.shareError': 'Error al compartir',
    'articles.shareErrorDesc': 'No se pudo compartir el artículo',
    'articles.translating': 'Traduciendo...',
    'articles.filters': 'Filtros',
    'articles.clearAll': 'Borrar todo',
    'articles.latest': 'Reciente',
    'articles.oldest': 'Antiguo',
    'articles.popular': 'Popular',
    'articles.latestFirst': 'Más reciente',
    'articles.oldestFirst': 'Más antiguo',
    'articles.mostPopular': 'Más popular',
    'articles.category': 'Categoría',
    'articles.author': 'Autor',
    'articles.showingOf': 'Mostrando {count} de {total} artículos',
    'articles.all': 'Todos',
    'articles.cat.matchAnalysis': 'Análisis de Partido',
    'articles.cat.transferNews': 'Noticias de Fichajes',
    'articles.cat.playerSpotlight': 'Jugador Destacado',
    'articles.cat.worldCup2026': 'Copa del Mundo 2026',
    'articles.cat.championsLeague': 'Liga de Campeones',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Tácticas',
    'articles.cat.opinion': 'Opinión',
    'articles.cat.didYouKnow': '¿Sabías que?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Negocio del Fútbol',
    'articles.cat.haiti': 'Haití',
    'articles.subtitle': 'Las últimas noticias, fichajes y análisis del fútbol mundial',
    'articles.searchPlaceholder': 'Buscar artículos...',
    'articles.noResults': 'No se encontraron artículos',
    'articles.tryDifferentSearch': 'Prueba con otro término o categoría',
    'articles.moreStories': 'Más historias',
    'articles.backToArticles': 'Volver a artículos',
    'articles.notFound': 'Artículo no encontrado',
    'articles.views': 'vistas',
    'articles.likes': 'Me gusta',
    'articles.similarArticles': 'Artículos similares',
    'articles.loginToLike': 'Inicio de sesión requerido',
    'articles.loginToLikeDesc': 'Por favor inicia sesión para dar me gusta',
    'articles.shareSuccess': 'Enlace del artículo copiado',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Pon a prueba tus conocimientos de fútbol con desafíos cronometrados',
    'quiz.noQuizzes': 'Aún no hay quizzes disponibles',
    'quiz.play': 'Jugar',
    'quiz.startQuiz': 'Comenzar Quiz',
    'quiz.loading': 'Cargando...',
    'quiz.notFound': 'Quiz no encontrado',
    'quiz.browseQuizzes': 'Ver Quizzes',
    'quiz.minutes': 'minutos',
    'quiz.answers': 'respuestas',
    'quiz.answer': 'Respuesta',
    'quiz.value': 'Valor',
    'quiz.typeAnswer': 'Escribe tu respuesta...',
    'quiz.giveUp': 'Rendirse',
    'quiz.hint': 'Pista',
    'quiz.loginForHint': 'Inicio de sesión requerido',
    'quiz.loginForHintDesc': 'Crea una cuenta para desbloquear pistas',
    'quiz.results': 'Resultados',
    'quiz.timeTaken': 'Tiempo',
    'quiz.playAgain': 'Jugar de Nuevo',
    'quiz.share': 'Compartir',
    'quiz.shareScore': 'Compartir Puntuación',
    'quiz.shareChallenge': '¿Puedes superar mi puntuación?',
    'quiz.linkCopied': '¡Enlace copiado!',

    // Common
    'common.back': 'Volver',
  },
  ht: {
    // Navbar
    'nav.home': 'Lakay',
    'nav.grenadiers': 'Les Grenadiers',
    // Grenadiers
    'gren.subtitle': 'Seleksyon nasyonal Ayiti',
    'gren.back': 'Lakay',
    'gren.players': 'jwè',
    'gren.statLines': 'liy estatistik',
    'gren.callupsWord': 'konvokasyon',
    'gren.tabSquad': 'Efektif',
    'gren.tabStats': 'Estatistik',
    'gren.tabCallups': 'Konvokasyon',
    'gren.posGk': 'Gadyen',
    'gren.posDef': 'Defansè',
    'gren.posMid': 'Milye',
    'gren.posAtt': 'Atakan',
    'gren.posOther': 'Lòt',
    'gren.currentClub': 'Klib aktyèl',
    'gren.clubCountry': 'Peyi klib la',
    'gren.birth': 'Nesans',
    'gren.birthPlace': 'Kote li fèt',
    'gren.marketValue': 'Valè sou mache',
    'gren.status': 'Estati',
    'gren.contract': 'Kontra',
    'gren.agent': 'Ajan',
    'gren.injuries': 'Blesi resan',
    'gren.career': 'Parkou',
    'gren.years': 'lane',
    'gren.merchPerso': 'Machandiz pèsonèl',
    'gren.merchClub': 'Machandiz klib',
    'gren.statsTitle': 'Estatistik',
    'gren.callupsTitle': 'Konvokasyon',
    'gren.thPlayer': 'Jwè',
    'gren.thSeason': 'Sezon',
    'gren.thCompetition': 'Konpetisyon',
    'gren.thClub': 'Klib/Sel.',
    'gren.thMp': 'MJ',
    'gren.thStarts': 'Tit',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Gòl',
    'gren.thAssists': 'PD',
    'gren.thYellow': 'KJ',
    'gren.thRed': 'KR',
    'gren.thRating': 'Nòt',
    'gren.thTournament': 'Tounwa',
    'gren.thDate': 'Dat',
    'gren.thOpponent': 'Advèsè',
    'gren.thLocation': 'Kote',
    'gren.thResult': 'Rezilta',
    'gren.thPresence': 'Prezans',
    'gren.tournament': 'Tounwa',
    'gren.allTournaments': 'Tout tounwa yo',
    'gren.matches': 'match',
    'gren.noStats': 'Pa gen estatistik disponib.',
    'gren.noCallups': 'Pa gen konvokasyon disponib.',
    'gren.present': 'Prezan',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Atik yo',
    'nav.askMenlifoot': 'Mande Menlifoot',
    'nav.store': 'Boutik',
    'nav.signIn': 'Konekte',
    'nav.login': 'Konekte',
    'nav.logout': 'Dekonekte',
    'nav.editorial': 'Editoryal',
    
    // Profile
    'profile.settings': 'Paramèt Pwofil',
    'profile.profile': 'Pwofil',
    'profile.security': 'Sekirite',
    'profile.avatarHint': 'Klike pou chanje avatar',
    'profile.displayName': 'Non Afichaj',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Di nou sou ou...',
    'profile.email': 'Imèl',
    'profile.save': 'Anrejistre Chanjman',
    'profile.changePassword': 'Chanje Modpas',
    'profile.currentPassword': 'Modpas Aktyèl',
    'profile.newPassword': 'Nouvo Modpas',
    'profile.confirmPassword': 'Konfime Modpas',
    'profile.updatePassword': 'Mete Modpas Ajou',
    'profile.removeAvatar': 'Retire',
    'profile.avatarRemoved': 'Avatar retire avèk siksè',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'Nouvo Epizòd Disponib',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Plonje nan bèl jwèt la ak analiz ekspè, entèvyou jwè, ak rezime match nan pi gwo lig nan mond lan.',
    'hero.listenNow': 'Koute Kounye a',
    'hero.browseEpisodes': 'Wè Epizòd yo',
    'hero.episodeTitle': 'Apèsi Koup di Mond 2026',
    'hero.episodeInfo': 'Epizòd 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Mizajou an Dirèk',
    'news.title': 'Dènye',
    'news.titleHighlight': 'Nouvèl',
    'news.description': 'Rete enfòme ak dènye nouvèl foutbòl nan mond lan',
    'news.worldCup': 'Koup di Mond 2026',
    'news.roadTo2026': 'Wout pou 2026',
    'news.wcDescription': 'Tout sa ou bezwen konnen sou pwochen Koup di Mond FIFA nan Etazini, Meksik ak Kanada.',
    'news.exploreCoverage': 'Eksplore Kouvèti',
    'news.latestQualifier': 'Dènye Rezilta Kalifikasyon',
    'news.latestUpdates': 'Dènye Mizajou',
    'news.viewAll': 'Wè Tout Nouvèl',
    'news.backToNews': 'Retounen nan Nouvèl',
    'news.backToHome': 'Retounen Lakay',
    'news.footballNews': 'Foutbòl',
    'news.newsTitle': 'Nouvèl',
    'news.newsDescription': 'Sous ou pou dènye nouvèl foutbòl, transfè ak rezilta match',
    'news.allNews': 'Tout Nouvèl',
    'news.transfers': 'Transfè',
    'news.championsLeague': 'Lig Chanpyon',
    'news.matches': 'Match',
    'news.injuries': 'Blesi',
    'news.noNews': 'Pa gen nouvèl disponib',
    'news.checkBack': 'Retounen pita pou mizajou',
    'news.searchPlaceholder': 'Chèche nouvèl...',
    'news.source': 'Sous',
    'news.by': 'Pa',
    'news.readFull': 'Li Atik Konplè',
    
    // Merch Section
    'merch.exclusive': 'Koleksyon Eksklizif',
    'merch.title': 'Boutik',
    'merch.titleHighlight': 'Ofisyèl',
    'merch.description': 'Montre pasyon ou ak pwodui Menlifoot premyòm. Edisyon limite ou pap jwenn okenn lòt kote.',
    'merch.shopNow': 'Achte',
    'merch.addToCart': 'Mete nan Panye',
    'merch.added': 'Ajoute nan panye',
    
    // Social Section
    'social.community': 'Rejwenn Kominote a',
    'social.title': 'Konekte',
    'social.titleHighlight': 'Avèk Nou',
    'social.description': 'Swiv vwayaj nou sou tout platfòm yo epi vin fè pati fanmi Menlifoot la.',
    'social.followers': 'moun kap swiv',
    'social.subscribers': 'abòne',
    
    // AI Agent
    'ai.title': 'Ekspè Menlifoot',
    'ai.subtitle': 'Pouvwa pa Prof Menlifoot',
    'ai.placeholder': 'Mande m nenpòt bagay sou foutbòl...',
    'ai.greeting': 'Sak pase! Mwen se Ekspè Menlifoot ou. Ou gen kesyon sou prediksyon match, estatistik jwè, nouvèl transfè, oswa Koup di Mond 2026? Ann pale foutbòl.',
    
    // Chat Section
    'chat.poweredBy': 'Pouvwa pa Prof Menlifoot',
    'chat.askThe': 'Mande',
    'chat.expertName': 'Ekspè Menlifoot la',
    'chat.description': 'Jwenn repons imedyat sou prediksyon match, estatistik jwè, nouvèl transfè, ak tout bagay sou foutbòl.',
    'chat.alwaysReady': 'Toujou pare pou ede',
    'chat.tryAsking': 'Eseye mande:',
    
    // Footer
    'footer.tagline': 'Patnè foutbòl final ou. Rete konekte ak bèl jwèt la atravè podcast, nouvèl, ak kominote.',
    'footer.company': 'Konpayi',
    'footer.content': 'Kontni',
    'footer.support': 'Sipò',
    'footer.aboutUs': 'Konsènan Nou',
    'footer.careers': 'Karyè',
    'footer.press': 'Laprès',
    'footer.contact': 'Kontakte',
    'footer.podcast': 'Podcast',
    'footer.news': 'Nouvèl',
    'footer.videos': 'Videyo',
    'footer.newsletter': 'Bilten',
    'footer.helpCenter': 'Sant Èd',
    'footer.privacyPolicy': 'Règ Konfidansyalite',
    'footer.termsOfService': 'Kondisyon Sèvis',
    'footer.cookiePolicy': 'Règ Cookie',
    'footer.editorial': 'Editoryal',
    'footer.emailPlaceholder': 'Antre imèl ou',
    'footer.rights': 'Tout dwa rezève.',
    
    // Splash
    'splash.companion': 'Patnè Foutbòl Ou',
    
    // Articles
    'articles.badge': 'Dènye Atik yo',
    'articles.title': 'Atik',
    'articles.titleHighlight': 'Vedèt',
    'articles.description': 'Analiz ekspè, pèspektiv ak istwa nan mond foutbòl la.',
    'articles.save': 'Sere',
    'articles.share': 'Pataje',
    'articles.saved': 'Sere',
    'articles.removed': 'Retire',
    'articles.addedToSaved': 'Atik ajoute nan sere yo',
    'articles.removedFromSaved': 'Atik retire nan sere yo',
    'articles.copied': 'Kopye',
    'articles.linkCopied': 'Lyen kopye nan pres-papye',
    'articles.keywords': 'Mo Kle',
    'articles.shared': 'Pataje',
    'articles.sharedSuccess': 'Atik pataje avèk siksè',
    'articles.shareError': 'Echèk pataj',
    'articles.shareErrorDesc': 'Pa kapab pataje atik la',
    'articles.translating': 'Ap tradui...',
    'articles.filters': 'Filtè',
    'articles.clearAll': 'Efase tout',
    'articles.latest': 'Dènye',
    'articles.oldest': 'Pi ansyen',
    'articles.popular': 'Popilè',
    'articles.latestFirst': 'Pi resan an premye',
    'articles.oldestFirst': 'Pi ansyen an premye',
    'articles.mostPopular': 'Pi popilè',
    'articles.category': 'Kategori',
    'articles.author': 'Otè',
    'articles.showingOf': 'Montre {count} sou {total} atik',
    'articles.all': 'Tout',
    'articles.cat.matchAnalysis': 'Analiz Match',
    'articles.cat.transferNews': 'Nouvèl Transfè',
    'articles.cat.playerSpotlight': 'Jwè an Vedèt',
    'articles.cat.worldCup2026': 'Koup di Mond 2026',
    'articles.cat.championsLeague': 'Lig Chanpyon',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Taktik',
    'articles.cat.opinion': 'Opinyon',
    'articles.cat.didYouKnow': 'Èske ou te konnen?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Biznis Foutbòl',
    'articles.cat.haiti': 'Ayiti',
    'articles.subtitle': 'Dènye nouvèl foutbòl, transfè ak analiz nan mond antye',
    'articles.searchPlaceholder': 'Chèche atik...',
    'articles.noResults': 'Pa jwenn okenn atik',
    'articles.tryDifferentSearch': 'Eseye yon lòt tèm oswa kategori',
    'articles.moreStories': 'Plis istwa',
    'articles.backToArticles': 'Retounen nan atik yo',
    'articles.notFound': 'Atik pa jwenn',
    'articles.views': 'vi',
    'articles.likes': 'Renmen',
    'articles.similarArticles': 'Atik menm jan',
    'articles.loginToLike': 'Koneksyon obligatwa',
    'articles.loginToLikeDesc': 'Tanpri konekte pou renmen atik yo',
    'articles.shareSuccess': 'Lyen atik kopye',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Teste konesans foutbòl ou ak defi kronometre',
    'quiz.noQuizzes': 'Pa gen quiz disponib ankò',
    'quiz.play': 'Jwe',
    'quiz.startQuiz': 'Kòmanse Quiz',
    'quiz.loading': 'Ap chaje...',
    'quiz.notFound': 'Quiz pa jwenn',
    'quiz.browseQuizzes': 'Wè Quiz yo',
    'quiz.minutes': 'minit',
    'quiz.answers': 'repons',
    'quiz.answer': 'Repons',
    'quiz.value': 'Valè',
    'quiz.typeAnswer': 'Tape repons ou...',
    'quiz.giveUp': 'Abandone',
    'quiz.hint': 'Endis',
    'quiz.loginForHint': 'Koneksyon obligatwa',
    'quiz.loginForHintDesc': 'Kreye yon kont pou debloke endis',
    'quiz.results': 'Rezilta',
    'quiz.timeTaken': 'Tan',
    'quiz.playAgain': 'Jwe Ankò',
    'quiz.share': 'Pataje',
    'quiz.shareScore': 'Pataje Rezilta',
    'quiz.shareChallenge': 'Èske ou ka bat rezilta mwen an?',
    'quiz.linkCopied': 'Lyen kopye!',

    // Common
    'common.back': 'Retounen',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('menlifoot-language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('menlifoot-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  fr: 'Français',
  es: 'Español',
  ht: 'Kreyòl',
};
