// Language context for multi-language support
import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es' | 'ht';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.grenadiers': 'Haiti',
    // Grenadiers
    'gren.subtitle': 'Haiti National Team',
    'gren.back': 'Home',
    'gren.players': 'players',
    'gren.statLines': 'stat lines',
    'gren.callupsWord': 'call-ups',
    'gren.tabSquad': 'Squad',
    'gren.tabStats': 'Statistics',
    'gren.tabCallups': 'Call-ups',
    'gren.posGk': 'Goalkeepers',
    'gren.posDef': 'Defenders',
    'gren.posMid': 'Midfielders',
    'gren.posAtt': 'Forwards',
    'gren.posOther': 'Others',
    'gren.currentClub': 'Current club',
    'gren.clubCountry': 'Club country',
    'gren.birth': 'Birth',
    'gren.birthPlace': 'Birthplace',
    'gren.marketValue': 'Market value',
    'gren.status': 'Status',
    'gren.contract': 'Contract',
    'gren.agent': 'Agent',
    'gren.injuries': 'Recent injuries',
    'gren.career': 'Career',
    'gren.years': 'yrs',
    'gren.merchPerso': 'Personal merch',
    'gren.merchClub': 'Club merch',
    'gren.statsTitle': 'Statistics',
    'gren.callupsTitle': 'Call-ups',
    'gren.thPlayer': 'Player',
    'gren.thSeason': 'Season',
    'gren.thCompetition': 'Competition',
    'gren.thClub': 'Club/Sel.',
    'gren.thMp': 'MP',
    'gren.thStarts': 'Starts',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Goals',
    'gren.thAssists': 'A',
    'gren.thYellow': 'YC',
    'gren.thRed': 'RC',
    'gren.thRating': 'Rating',
    'gren.thTournament': 'Tournament',
    'gren.thDate': 'Date',
    'gren.thOpponent': 'Opponent',
    'gren.thLocation': 'Venue',
    'gren.thResult': 'Result',
    'gren.thPresence': 'Presence',
    'gren.tournament': 'Tournament',
    'gren.allTournaments': 'All tournaments',
    'gren.matches': 'match(es)',
    'gren.noStats': 'No statistics available.',
    'gren.noCallups': 'No call-ups available.',
    'gren.present': 'Present',
    // rebrand app
    'nav.listen': 'Listen', 'nav.shop': 'Shop', 'nav.me': 'Me',
    'home.askTitle': 'Ask Menlifoot', 'home.askSub': 'Anything about the game — squads, history, tactics.',
    'auth.signin': 'Sign in', 'auth.signup': 'Sign up', 'auth.welcome': 'Welcome back', 'auth.createTitle': 'Create your account', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.signinBtn': 'Sign in', 'auth.signupBtn': 'Create account', 'auth.checkEmail': 'Check your email to confirm your account.', 'auth.needEmail': 'Enter your email and password.',
    'home.leadStory': 'Lead story', 'home.latest': 'Latest', 'home.allAnalysis': 'All analysis',
    'home.podcastNew': 'Podcast · new episode', 'home.shopDrop': 'Shop · launch drop', 'home.seeAll': 'See all',
    'ask.title': 'Ask Menlifoot', 'ask.sub': 'Trained on our archive · answers cite sources',
    'ask.intro': "I'm Menlifoot — ask me anything about the game: squads, history, tactics, the Grenadiers.",
    'ask.placeholder': 'Ask about a match, a squad, a stat…', 'ask.error': 'My bad, something went wrong. Try again!',
    'ask.p1': 'Who is the Haiti captain?', 'ask.p2': 'Who won the 2022 World Cup?', 'ask.p3': 'Explain the offside rule',
    'listen.original': 'Menlifoot original', 'listen.title': 'Podcast', 'listen.episodes': 'Episodes', 'listen.watch': 'Watch · interviews',
    'shop.nowOpen': 'Now open', 'shop.store': 'Store', 'shop.bag': 'Bag', 'shop.limited': 'Limited', 'shop.size': 'Size', 'shop.add': 'Add',
    'shop.yourBag': 'Your bag', 'shop.subtotal': 'Subtotal', 'shop.shipping': 'Shipping', 'shop.total': 'Total',
    'shop.checkout': 'Checkout now', 'shop.secure': 'Secure checkout · Stripe', 'shop.empty': 'Nothing in the bag yet', 'shop.remove': 'Remove', 'shop.similar': 'You might also like', 'shop.personalize': 'Personalize it', 'shop.personalizePlaceholder': 'Your name or number', 'shop.personalizeHint': 'Add a name/number and we’ll print it on your item.', 'shop.personalized': 'Personalized', 'shop.favorited': 'Added to favorites', 'shop.linkCopied': 'Link copied!', 'shop.addedToCart': 'Added to cart', 'shop.viewCart': 'View cart', 'shop.search': 'Search products', 'shop.all': 'All categories', 'shop.featured': 'Featured', 'shop.priceLow': 'Price: low to high', 'shop.priceHigh': 'Price: high to low', 'shop.nameAz': 'Name: A–Z', 'shop.noResults': 'No products match.', 'shop.qty': 'Quantity',
    'shop.emptyDesc': 'The launch drop is live — caps, tees and the podcast crewneck.', 'shop.browse': 'Browse the store',
    'shop.confirmed': 'Order confirmed', 'shop.confirmedDesc': "#MLF-2841 · confirmation sent. You'll get tracking within 24 hours.",
    'shop.backStore': 'Back to store', 'shop.soon': 'Launching soon', 'shop.shippingTo': 'Shipping to', 'shop.firstName': 'First name', 'shop.lastName': 'Last name', 'shop.email': 'Email', 'shop.phone': 'Phone', 'shop.address': 'Address', 'shop.address2': 'Apt, suite (optional)', 'shop.city': 'City', 'shop.zip': 'ZIP', 'shop.region': 'State / Region', 'shop.country': 'Country', 'shop.pay': 'Continue to payment', 'shop.color': 'Color', 'shop.soonDesc': 'The Menlifoot drop is on the way — check back shortly.', 'shop.fAll': 'All', 'shop.fApparel': 'Apparel', 'shop.fCaps': 'Caps', 'shop.fAccessories': 'Accessories',
    'me.saved': 'Saved', 'me.read': 'Read', 'me.streak': 'Streak', 'me.savedArticles': 'Saved articles', 'me.orders': 'Order history', 'me.noOrders': 'No orders yet.', 'me.noSaved': 'No saved articles yet.', 'me.memberSince': 'Member since', 'me.liked': 'Liked articles', 'me.noLiked': 'No liked articles yet.', 'me.comments': 'Your comments', 'me.noComments': 'No comments yet.', 'me.preferences': 'Preferences', 'me.activity': 'Activity', 'me.currentPassword': 'Current password', 'me.currentPasswordHint': 'Required to change your email or password.', 'me.needCurrentPw': 'Enter your current password first.', 'me.wrongPw': 'Current password is incorrect.', 'me.email': 'Email', 'me.newPassword': 'New password', 'me.update': 'Update', 'me.emailUpdated': 'Check your new email to confirm the change.', 'me.passwordUpdated': 'Password updated.', 'me.pwShort': 'Password must be at least 6 characters.', 'order.processing': 'Processing', 'order.preparing': 'In preparation', 'order.shipped': 'Shipped', 'order.delivered': 'Delivered', 'order.canceled': 'Canceled', 'order.tracking': 'Tracking', 'me.history': 'Reading history',
    'me.notifications': 'Notifications', 'me.language': 'Language', 'me.signIn': 'Sign in', 'me.signOut': 'Sign out',
    'me.notSignedIn': 'Not signed in', 'me.member': 'Member', 'me.plus': 'Menlifoot+',
    'me.plusDesc': 'Ad-free reading, early episode drops, 10% off every order.', 'me.plusPrice': '$4.99 / month',
    'gren.nationalTeam': 'National team', 'gren.followTeam': 'Follow team', 'gren.following': 'Following', 'gren.lastMatch': 'Last match',
    'gren.rRecords': 'Records', 'gren.rResults': 'Results', 'gren.rSquad': 'Squad', 'gren.rUpcoming': 'Upcoming', 'gren.allTimeGoals': 'All-time goals',
    'gren.mostCaps': 'Most caps', 'gren.caps': 'caps', 'gren.desc': 'Fixtures, call-ups and a profile for every player in the Haitian selection — clubs, caps, goals, market value.',
    'art.askPiece': 'Ask Menli about this piece',
    'art.comments': 'Comments', 'art.writeComment': 'Write a comment…', 'art.post': 'Post', 'art.noComments': 'Be the first to comment.', 'art.linkCopied': 'Link copied!', 'art.saved': 'Saved to your bookmarks.', 'art.copyLink': 'Copy link', 'art.shareVia': 'Share…',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Articles',
    'nav.askMenlifoot': 'Ask Menlifoot',
    'nav.store': 'Store',
    'nav.signIn': 'Sign In',
    'nav.login': 'Login',
    'nav.logout': 'Sign Out',
    'nav.editorial': 'Editorial',
    
    // Profile
    'profile.settings': 'Profile Settings',
    'profile.profile': 'Profile',
    'profile.security': 'Security',
    'profile.avatarHint': 'Click to change avatar',
    'profile.displayName': 'Display Name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.email': 'Email',
    'profile.save': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.updatePassword': 'Update Password',
    'profile.removeAvatar': 'Remove',
    'profile.avatarRemoved': 'Avatar removed successfully',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'New Episode Available',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Dive deep into the beautiful game with expert analysis, player interviews, and match breakdowns from the world\'s biggest leagues.',
    'hero.listenNow': 'Listen Now',
    'hero.browseEpisodes': 'Browse Episodes',
    'hero.episodeTitle': 'World Cup 2026 Preview',
    'hero.episodeInfo': 'Episode 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Live Updates',
    'news.title': 'Latest',
    'news.titleHighlight': 'News',
    'news.description': 'Stay updated with the latest soccer news from around the world',
    'news.worldCup': 'World Cup 2026',
    'news.roadTo2026': 'The Road to 2026',
    'news.wcDescription': 'Everything you need to know about the upcoming FIFA World Cup hosted across USA, Mexico, and Canada.',
    'news.exploreCoverage': 'Explore Coverage',
    'news.latestQualifier': 'Latest Qualifier Results',
    'news.latestUpdates': 'Latest Updates',
    'news.viewAll': 'View All News',
    'news.backToNews': 'Back to News',
    'news.backToHome': 'Back to Home',
    'news.footballNews': 'Football',
    'news.newsTitle': 'News',
    'news.newsDescription': 'Your source for the latest football news, transfers, and match updates',
    'news.allNews': 'All News',
    'news.transfers': 'Transfers',
    'news.championsLeague': 'Champions League',
    'news.matches': 'Matches',
    'news.injuries': 'Injuries',
    'news.noNews': 'No news available',
    'news.checkBack': 'Check back later for updates',
    'news.searchPlaceholder': 'Search news...',
    'news.source': 'Source',
    'news.by': 'By',
    'news.readFull': 'Read Full Article',
    
    // Merch Section
    'merch.exclusive': 'Exclusive Drops',
    'merch.title': 'Official',
    'merch.titleHighlight': 'Merch',
    'merch.description': 'Rep your passion with premium Menlifoot gear. Limited edition drops you won\'t find anywhere else.',
    'merch.shopNow': 'Shop Now',
    'merch.addToCart': 'Add to Cart',
    'merch.added': 'Added to cart',
    
    // Social Section
    'social.community': 'Join the Community',
    'social.title': 'Connect',
    'social.titleHighlight': 'With Us',
    'social.description': 'Follow our journey across platforms and become part of the Menlifoot family.',
    'social.followers': 'followers',
    'social.subscribers': 'subscribers',
    
    // AI Agent
    'ai.title': 'Menlifoot Expert',
    'ai.subtitle': 'Powered by Prof Menlifoot',
    'ai.placeholder': 'Ask me anything about soccer...',
    'ai.greeting': 'Hey! I\'m your Menlifoot Expert. Got questions about match predictions, player stats, transfer news, or World Cup 2026? Let\'s talk football.',
    
    // Chat Section
    'chat.poweredBy': 'Powered by Prof Menlifoot',
    'chat.askThe': 'Ask the',
    'chat.expertName': 'Menlifoot Expert',
    'chat.description': 'Get instant answers about match predictions, player stats, transfer news, tactics, and everything football.',
    'chat.alwaysReady': 'Always ready to help',
    'chat.tryAsking': 'Try asking:',
    
    // Footer
    'footer.tagline': 'Football, differently — stay connected to the beautiful game.',
    'footer.company': 'Company',
    'footer.content': 'Content',
    'footer.support': 'Support',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.contact': 'Contact',
    'footer.podcast': 'Podcast',
    'footer.news': 'News',
    'footer.videos': 'Videos',
    'footer.newsletter': 'Newsletter',
    'footer.helpCenter': 'Help Center',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.editorial': 'Editorial',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.rights': 'All rights reserved.',
    
    // Splash
    'splash.companion': 'Football, differently',
    
    // Articles
    'articles.badge': 'Latest Articles',
    'articles.title': 'Featured',
    'articles.titleHighlight': 'Articles',
    'articles.description': 'Expert insights, analysis, and stories from the world of football.',
    'articles.save': 'Save',
    'articles.share': 'Share',
    'articles.saved': 'Saved',
    'articles.removed': 'Removed',
    'articles.addedToSaved': 'Article added to saved',
    'articles.removedFromSaved': 'Article removed from saved',
    'articles.copied': 'Copied',
    'articles.linkCopied': 'Link copied to clipboard',
    'articles.keywords': 'Keywords',
    'articles.shared': 'Shared',
    'articles.sharedSuccess': 'Article shared successfully',
    'articles.shareError': 'Share failed',
    'articles.shareErrorDesc': 'Could not share the article',
    'articles.translating': 'Translating...',
    'articles.filters': 'Filters',
    'articles.clearAll': 'Clear all',
    'articles.latest': 'Latest',
    'articles.oldest': 'Oldest',
    'articles.popular': 'Popular',
    'articles.latestFirst': 'Latest First',
    'articles.oldestFirst': 'Oldest First',
    'articles.mostPopular': 'Most Popular',
    'articles.category': 'Category',
    'articles.author': 'Author',
    'articles.showingOf': 'Showing {count} of {total} articles',
    'articles.all': 'All',
    'articles.cat.matchAnalysis': 'Match Analysis',
    'articles.cat.transferNews': 'Transfer News',
    'articles.cat.playerSpotlight': 'Player Spotlight',
    'articles.cat.worldCup2026': 'World Cup 2026',
    'articles.cat.championsLeague': 'Champions League',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Tactics',
    'articles.cat.opinion': 'Opinion',
    'articles.cat.didYouKnow': 'Did You Know?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Football Business',
    'articles.cat.lifestyle': 'Lifestyle',
    'articles.cat.haiti': 'Haiti',
    'ucl.eyebrow': 'Rate your team free',
    'ucl.title': 'How good is your squad?',
    'ucl.subtitle': 'Get a rating out of 100, see what is costing you points, and find the transfers to fix it.',
    'ucl.importScreenshot': 'Import from screenshot',
    'ucl.buildManually': 'Build manually',
    'ucl.importTitle': 'Import your squad',
    'ucl.importHelp': 'Upload a screenshot of your fantasy team. We read the players, your captain and your bench.',
    'ucl.chooseImage': 'Choose image',
    'ucl.buildTitle': 'Build your squad',
    'ucl.formation': 'Formation',
    'ucl.budget': 'Budget',
    'ucl.credit': 'credit',
    'ucl.optimizeLockedBody': 'The strongest XI and captain from the 15 you already own.',
    'ucl.captainLockedBody': 'Your three best captain picks, ranked by fixture and form.',
    'ucl.chipLockedBody': 'Whether to play Wildcard or Limitless this matchday, or hold.',
    'ucl.bestPicksLockedBody': 'The best players to own this matchday, ranked by position.',
    'ucl.credits': 'credits',
    'ucl.unlock': 'Unlock',
    'ucl.signIn': 'Sign in',
    'ucl.signInToUnlock': 'Create a free account and get 10 credits to unlock this.',
    'ucl.notEnoughCredits': 'Not enough credits.',
    'ucl.topUp': 'Top up',
    'ucl.topUpPrompt': 'Top up to keep analysing — 15 credits for $0.99.',
    'ucl.moreTransfersAvailable': 'more transfer suggestions available',
    'ucl.bestPicksNoFixtures': 'The schedule is not published yet, so this is ranked on club form, not opponents.',
    'ucl.bestPicksTitle': 'Fixture analysis — best picks',
    'ucl.bestPicksBody': 'Strongest players to own this matchday, ranked by fixture, club form and availability.',
    'ucl.cleanSheets': 'clean sheets',
    'ucl.goalsPerGame': 'goals per game',
    'ucl.score.gk': 'Goalkeepers',
    'ucl.score.def': 'Defenders',
    'ucl.score.mid': 'Midfielders',
    'ucl.score.fwd': 'Forwards',
    'ucl.remaining': 'Remaining',
    'ucl.overBudget': 'Over budget by',
    'ucl.pricesPending': 'Prices not published yet',
    'ucl.partialPrices': 'priced',
    'ucl.bench': 'Bench',
    'ucl.addPlayer': 'Add',
    'ucl.unknown': 'Unknown',
    'ucl.pickCaptain': 'Pick your captain',
    'ucl.searchPlayer': 'Search player',
    'ucl.loading': 'Loading...',
    'ucl.noPlayers': 'No players found',
    'ucl.playersPicked': 'picked',
    'ucl.needCaptain': 'Pick a captain',
    'ucl.rateMyTeam': 'Rate my team',
    'ucl.fixManually': 'Fix it manually instead',
    'ucl.couldNotRead': 'Could not read these players',
    'ucl.reviewNeeded': 'Needs a quick check',
    'ucl.reviewNeededBody': 'We could not read every player. Review the squad before rating.',
    'ucl.holdOn': 'Hold on',
    'ucl.analyzingTitle': 'Analysing your team',
    'ucl.analyzing': 'Analysing...',
    'ucl.stage.reading': 'Reading your squad',
    'ucl.stage.measuring': 'Measuring the damage',
    'ucl.stage.finding': 'Finding your way back',
    'ucl.teamRated': 'Your team is rated',
    'ucl.breakdown': 'Breakdown',
    'ucl.score.captain': 'Captain choice',
    'ucl.score.availability': 'Availability',
    'ucl.score.form': 'Form',
    'ucl.score.fixtures': 'Fixtures',
    'ucl.score.structure': 'Squad structure',
    'ucl.score.diversity': 'Club spread',
    'ucl.score.value': 'Value',
    'ucl.transfers': 'Suggested transfers',
    'ucl.rateAnother': 'Rate another team',
    'ucl.startOver': 'Start over',
    'ucl.error': 'Something went wrong',
    'ucl.viewFixtures': 'View fixtures',
    'ucl.fixturesTitle': 'Fixtures',
    'ucl.matchday': 'Matchday',
    'ucl.deadline': 'Deadline',
    'ucl.localTimes': 'All times shown in your local time',
    'ucl.previousMatchday': 'Previous matchday',
    'ucl.nextMatchday': 'Next matchday',
    'ucl.noFixtures': 'The league phase schedule has not been published yet.',
    'ucl.tbd': 'Date to be confirmed',
    'ucl.orPaste': 'or press Ctrl+V to paste a screenshot',
    'ucl.optimizeTitle': 'Optimise my team',
    'ucl.optimizeBody': 'We can rearrange the 15 players you already own into a stronger starting XI:',
    'ucl.optimizeApply': 'Apply and re-score',
    'ucl.optimizeAlready': 'Your line-up is already the strongest arrangement of these 15 players.',
    'ucl.optimizeAnyway': 'Re-check my line-up',
    'ucl.captainTitle': 'Best captain options',
    'ucl.chipTitle': 'Chip advice',
    'ucl.chipHold': 'Hold your chips',
    'ucl.vs': 'vs',
    'ucl.difficulty': 'difficulty',
    'ucl.showMore': 'Show more',
    'articles.cat.uncategorized': 'Uncategorized',
    'articles.subtitle': 'The latest football news, transfers, and analysis from around the world',
    'articles.searchPlaceholder': 'Search articles...',
    'articles.noResults': 'No articles found',
    'articles.tryDifferentSearch': 'Try a different search term or category',
    'articles.moreStories': 'More Stories',
    'articles.backToArticles': 'Back to Articles',
    'articles.notFound': 'Article not found',
    'articles.views': 'views',
    'articles.likes': 'Likes',
    'articles.similarArticles': 'Similar Articles',
    'articles.loginToLike': 'Login required',
    'articles.loginToLikeDesc': 'Please login to like articles',
    'articles.shareSuccess': 'Article link copied to clipboard',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Test your football knowledge with timed trivia challenges',
    'quiz.noQuizzes': 'No quizzes available yet',
    'quiz.play': 'Play',
    'quiz.startQuiz': 'Start Quiz',
    'quiz.loading': 'Loading...',
    'quiz.notFound': 'Quiz not found',
    'quiz.browseQuizzes': 'Browse Quizzes',
    'quiz.minutes': 'minutes',
    'quiz.answers': 'answers',
    'quiz.answer': 'Answer',
    'quiz.value': 'Value',
    'quiz.typeAnswer': 'Type your answer...',
    'quiz.giveUp': 'Give Up',
    'quiz.hint': 'Hint',
    'quiz.loginForHint': 'Login required',
    'quiz.loginForHintDesc': 'Create an account to unlock hints',
    'quiz.results': 'Results',
    'quiz.timeTaken': 'Time',
    'quiz.playAgain': 'Play Again',
    'quiz.share': 'Share',
    'quiz.shareScore': 'Share Score',
    'quiz.shareChallenge': 'Can you beat my score?',
    'quiz.linkCopied': 'Link copied!',

    // Common
    'common.back': 'Back',
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.grenadiers': 'Haiti',
    // Grenadiers
    'gren.subtitle': 'Sélection nationale d\'Haïti',
    'gren.back': 'Accueil',
    'gren.players': 'joueurs',
    'gren.statLines': 'lignes de stats',
    'gren.callupsWord': 'convocations',
    'gren.tabSquad': 'Effectif',
    'gren.tabStats': 'Statistiques',
    'gren.tabCallups': 'Convocations',
    'gren.posGk': 'Gardiens',
    'gren.posDef': 'Défenseurs',
    'gren.posMid': 'Milieux',
    'gren.posAtt': 'Attaquants',
    'gren.posOther': 'Autres',
    'gren.currentClub': 'Club actuel',
    'gren.clubCountry': 'Pays du club',
    'gren.birth': 'Naissance',
    'gren.birthPlace': 'Lieu de naissance',
    'gren.marketValue': 'Valeur marchande',
    'gren.status': 'Statut',
    'gren.contract': 'Contrat',
    'gren.agent': 'Agent',
    'gren.injuries': 'Blessures récentes',
    'gren.career': 'Parcours',
    'gren.years': 'ans',
    'gren.merchPerso': 'Merch perso',
    'gren.merchClub': 'Merch club',
    'gren.statsTitle': 'Statistiques',
    'gren.callupsTitle': 'Convocations',
    'gren.thPlayer': 'Joueur',
    'gren.thSeason': 'Saison',
    'gren.thCompetition': 'Compétition',
    'gren.thClub': 'Club/Sél.',
    'gren.thMp': 'MJ',
    'gren.thStarts': 'Titu',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Buts',
    'gren.thAssists': 'PD',
    'gren.thYellow': 'CJ',
    'gren.thRed': 'CR',
    'gren.thRating': 'Note',
    'gren.thTournament': 'Tournoi',
    'gren.thDate': 'Date',
    'gren.thOpponent': 'Adversaire',
    'gren.thLocation': 'Lieu',
    'gren.thResult': 'Résultat',
    'gren.thPresence': 'Présence',
    'gren.tournament': 'Tournoi',
    'gren.allTournaments': 'Tous les tournois',
    'gren.matches': 'match(s)',
    'gren.noStats': 'Aucune statistique disponible.',
    'gren.noCallups': 'Aucune convocation disponible.',
    'gren.present': 'Présent',
    // rebrand app
    'nav.listen': 'Écouter', 'nav.shop': 'Boutique', 'nav.me': 'Moi',
    'home.askTitle': 'Demander Menlifoot', 'home.askSub': 'Tout sur le jeu — effectifs, histoire, tactique.',
    'auth.signin': 'Connexion', 'auth.signup': "S'inscrire", 'auth.welcome': 'Bon retour', 'auth.createTitle': 'Créer votre compte', 'auth.email': 'E-mail', 'auth.password': 'Mot de passe', 'auth.signinBtn': 'Se connecter', 'auth.signupBtn': 'Créer un compte', 'auth.checkEmail': 'Vérifiez votre e-mail pour confirmer votre compte.', 'auth.needEmail': 'Entrez votre e-mail et votre mot de passe.',
    'home.leadStory': 'À la une', 'home.latest': 'Derniers', 'home.allAnalysis': 'Toutes les analyses',
    'home.podcastNew': 'Podcast · nouvel épisode', 'home.shopDrop': 'Boutique · lancement', 'home.seeAll': 'Voir tout',
    'ask.title': 'Demander Menlifoot', 'ask.sub': 'Formé sur nos archives · réponses sourcées',
    'ask.intro': "Je suis Menlifoot — demandez-moi tout sur le foot : effectifs, histoire, tactique, les Grenadiers.",
    'ask.placeholder': 'Un match, un effectif, une stat…', 'ask.error': 'Oups, un problème est survenu. Réessayez !',
    'ask.p1': "Qui est le capitaine d'Haïti ?", 'ask.p2': 'Qui a gagné la Coupe du monde 2022 ?', 'ask.p3': 'Explique la règle du hors-jeu',
    'listen.original': 'Original Menlifoot', 'listen.title': 'Podcast', 'listen.episodes': 'Épisodes', 'listen.watch': 'Regarder · entretiens',
    'shop.nowOpen': 'Ouvert', 'shop.store': 'Boutique', 'shop.bag': 'Panier', 'shop.limited': 'Limité', 'shop.size': 'Taille', 'shop.add': 'Ajouter',
    'shop.yourBag': 'Votre panier', 'shop.subtotal': 'Sous-total', 'shop.shipping': 'Livraison', 'shop.total': 'Total',
    'shop.checkout': 'Payer maintenant', 'shop.secure': 'Paiement sécurisé · Stripe', 'shop.empty': 'Panier vide', 'shop.remove': 'Retirer', 'shop.similar': 'Vous aimerez aussi', 'shop.personalize': 'Personnaliser', 'shop.personalizePlaceholder': 'Votre nom ou numéro', 'shop.personalizeHint': 'Ajoutez un nom/numéro et nous l’imprimerons sur votre article.', 'shop.personalized': 'Personnalisé', 'shop.favorited': 'Ajouté aux favoris', 'shop.linkCopied': 'Lien copié !', 'shop.addedToCart': 'Ajouté au panier', 'shop.viewCart': 'Voir le panier', 'shop.search': 'Rechercher', 'shop.all': 'Toutes catégories', 'shop.featured': 'En vedette', 'shop.priceLow': 'Prix : croissant', 'shop.priceHigh': 'Prix : décroissant', 'shop.nameAz': 'Nom : A–Z', 'shop.noResults': 'Aucun produit.', 'shop.qty': 'Quantité',
    'shop.emptyDesc': 'Le lancement est là — casquettes, t-shirts et le sweat du podcast.', 'shop.browse': 'Voir la boutique',
    'shop.confirmed': 'Commande confirmée', 'shop.confirmedDesc': '#MLF-2841 · confirmation envoyée. Suivi sous 24 h.',
    'shop.backStore': 'Retour boutique', 'shop.soon': 'Bientôt disponible', 'shop.shippingTo': 'Livraison', 'shop.firstName': 'Prénom', 'shop.lastName': 'Nom', 'shop.email': 'E-mail', 'shop.phone': 'Téléphone', 'shop.address': 'Adresse', 'shop.address2': 'App, suite (facultatif)', 'shop.city': 'Ville', 'shop.zip': 'Code postal', 'shop.region': 'État / Région', 'shop.country': 'Pays', 'shop.pay': 'Continuer vers le paiement', 'shop.color': 'Couleur', 'shop.soonDesc': 'La collection Menlifoot arrive — revenez bientôt.', 'shop.fAll': 'Tout', 'shop.fApparel': 'Vêtements', 'shop.fCaps': 'Casquettes', 'shop.fAccessories': 'Accessoires',
    'me.saved': 'Enreg.', 'me.read': 'Lus', 'me.streak': 'Série', 'me.savedArticles': 'Articles enregistrés', 'me.orders': 'Historique des commandes', 'me.noOrders': 'Aucune commande.', 'me.noSaved': 'Aucun article enregistré.', 'me.memberSince': 'Membre depuis', 'me.liked': 'Articles aimés', 'me.noLiked': 'Aucun article aimé.', 'me.comments': 'Vos commentaires', 'me.noComments': 'Aucun commentaire.', 'me.preferences': 'Préférences', 'me.activity': 'Activité', 'me.currentPassword': 'Mot de passe actuel', 'me.currentPasswordHint': 'Requis pour changer votre e-mail ou mot de passe.', 'me.needCurrentPw': 'Entrez d’abord votre mot de passe actuel.', 'me.wrongPw': 'Mot de passe actuel incorrect.', 'me.email': 'E-mail', 'me.newPassword': 'Nouveau mot de passe', 'me.update': 'Mettre à jour', 'me.emailUpdated': 'Vérifiez votre nouvel e-mail pour confirmer.', 'me.passwordUpdated': 'Mot de passe mis à jour.', 'me.pwShort': 'Le mot de passe doit comporter au moins 6 caractères.', 'order.processing': 'En traitement', 'order.preparing': 'En préparation', 'order.shipped': 'Expédiée', 'order.delivered': 'Livrée', 'order.canceled': 'Annulée', 'order.tracking': 'Suivi', 'me.history': 'Historique de lecture',
    'me.notifications': 'Notifications', 'me.language': 'Langue', 'me.signIn': 'Connexion', 'me.signOut': 'Déconnexion',
    'me.notSignedIn': 'Non connecté', 'me.member': 'Membre', 'me.plus': 'Menlifoot+',
    'me.plusDesc': 'Lecture sans pub, épisodes en avant-première, 10 % sur chaque commande.', 'me.plusPrice': '4,99 $ / mois',
    'gren.nationalTeam': 'Sélection nationale', 'gren.followTeam': "Suivre l'équipe", 'gren.following': 'Suivi', 'gren.lastMatch': 'Dernier match',
    'gren.rRecords': 'Records', 'gren.rResults': 'Résultats', 'gren.rSquad': 'Effectif', 'gren.rUpcoming': 'À venir', 'gren.allTimeGoals': 'Buts (tous temps)',
    'gren.mostCaps': 'Plus de sélections', 'gren.caps': 'sél.', 'gren.desc': 'Calendrier, convocations et un profil pour chaque joueur de la sélection haïtienne — clubs, sélections, buts, valeur marchande.',
    'art.askPiece': 'Demander Menli sur cet article',
    'art.comments': 'Commentaires', 'art.writeComment': 'Écrire un commentaire…', 'art.post': 'Publier', 'art.noComments': 'Soyez le premier à commenter.', 'art.linkCopied': 'Lien copié !', 'art.saved': 'Ajouté à vos favoris.', 'art.copyLink': 'Copier le lien', 'art.shareVia': 'Partager…',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Articles',
    'nav.askMenlifoot': 'Demander Menlifoot',
    'nav.store': 'Boutique',
    'nav.signIn': 'Connexion',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.editorial': 'Éditorial',
    
    // Profile
    'profile.settings': 'Paramètres du profil',
    'profile.profile': 'Profil',
    'profile.security': 'Sécurité',
    'profile.avatarHint': 'Cliquez pour changer l\'avatar',
    'profile.displayName': 'Nom d\'affichage',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Parlez-nous de vous...',
    'profile.email': 'Email',
    'profile.save': 'Enregistrer',
    'profile.changePassword': 'Changer le mot de passe',
    'profile.currentPassword': 'Mot de passe actuel',
    'profile.newPassword': 'Nouveau mot de passe',
    'profile.confirmPassword': 'Confirmer le mot de passe',
    'profile.updatePassword': 'Mettre à jour le mot de passe',
    'profile.removeAvatar': 'Supprimer',
    'profile.avatarRemoved': 'Avatar supprimé avec succès',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'Nouvel Épisode Disponible',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Plongez dans le beau jeu avec des analyses d\'experts, des interviews de joueurs et des analyses de matchs des plus grandes ligues du monde.',
    'hero.listenNow': 'Écouter',
    'hero.browseEpisodes': 'Parcourir les Épisodes',
    'hero.episodeTitle': 'Aperçu Coupe du Monde 2026',
    'hero.episodeInfo': 'Épisode 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Mises à Jour en Direct',
    'news.title': 'Dernières',
    'news.titleHighlight': 'Actualités',
    'news.description': 'Restez informé des dernières actualités du football mondial',
    'news.worldCup': 'Coupe du Monde 2026',
    'news.roadTo2026': 'La Route vers 2026',
    'news.wcDescription': 'Tout ce que vous devez savoir sur la prochaine Coupe du Monde FIFA organisée aux États-Unis, au Mexique et au Canada.',
    'news.exploreCoverage': 'Explorer la Couverture',
    'news.latestQualifier': 'Derniers Résultats des Qualifications',
    'news.latestUpdates': 'Dernières Mises à Jour',
    'news.viewAll': 'Voir Toutes les Actualités',
    'news.backToNews': 'Retour aux Actualités',
    'news.backToHome': 'Retour à l\'Accueil',
    'news.footballNews': 'Football',
    'news.newsTitle': 'Actualités',
    'news.newsDescription': 'Votre source pour les dernières actualités, transferts et résultats de football',
    'news.allNews': 'Toutes les Actualités',
    'news.transfers': 'Transferts',
    'news.championsLeague': 'Ligue des Champions',
    'news.matches': 'Matchs',
    'news.injuries': 'Blessures',
    'news.noNews': 'Aucune actualité disponible',
    'news.checkBack': 'Revenez plus tard pour les mises à jour',
    'news.searchPlaceholder': 'Rechercher des nouvelles...',
    'news.source': 'Source',
    'news.by': 'Par',
    'news.readFull': 'Lire l\'Article Complet',
    
    // Merch Section
    'merch.exclusive': 'Collections Exclusives',
    'merch.title': 'Boutique',
    'merch.titleHighlight': 'Officielle',
    'merch.description': 'Montrez votre passion avec des articles Menlifoot premium. Éditions limitées introuvables ailleurs.',
    'merch.shopNow': 'Acheter',
    'merch.addToCart': 'Ajouter au Panier',
    'merch.added': 'Ajouté au panier',
    
    // Social Section
    'social.community': 'Rejoignez la Communauté',
    'social.title': 'Connectez',
    'social.titleHighlight': '-vous',
    'social.description': 'Suivez notre parcours sur toutes les plateformes et faites partie de la famille Menlifoot.',
    'social.followers': 'abonnés',
    'social.subscribers': 'abonnés',
    
    // AI Agent
    'ai.title': 'Expert Menlifoot',
    'ai.subtitle': 'Propulsé par Prof Menlifoot',
    'ai.placeholder': 'Posez-moi une question sur le football...',
    'ai.greeting': 'Salut! Je suis votre Expert Menlifoot. Des questions sur les prédictions de matchs, les stats des joueurs, les nouvelles de transferts ou la Coupe du Monde 2026? Parlons football.',
    
    // Chat Section
    'chat.poweredBy': 'Propulsé par Prof Menlifoot',
    'chat.askThe': 'Demandez à',
    'chat.expertName': 'l\'Expert Menlifoot',
    'chat.description': 'Obtenez des réponses instantanées sur les prédictions de matchs, statistiques de joueurs, actualités transferts et tout le football.',
    'chat.alwaysReady': 'Toujours prêt à aider',
    'chat.tryAsking': 'Essayez de demander:',
    
    // Footer
    'footer.tagline': 'Votre compagnon football ultime. Restez connecté au beau jeu grâce aux podcasts, actualités et communauté.',
    'footer.company': 'Entreprise',
    'footer.content': 'Contenu',
    'footer.support': 'Support',
    'footer.aboutUs': 'À Propos',
    'footer.careers': 'Carrières',
    'footer.press': 'Presse',
    'footer.contact': 'Contact',
    'footer.podcast': 'Podcast',
    'footer.news': 'Actualités',
    'footer.videos': 'Vidéos',
    'footer.newsletter': 'Newsletter',
    'footer.helpCenter': 'Centre d\'Aide',
    'footer.privacyPolicy': 'Politique de Confidentialité',
    'footer.termsOfService': 'Conditions d\'Utilisation',
    'footer.cookiePolicy': 'Politique des Cookies',
    'footer.editorial': 'Éditorial',
    'footer.emailPlaceholder': 'Entrez votre email',
    'footer.rights': 'Tous droits réservés.',
    
    // Splash
    'splash.companion': 'Le football autrement',
    
    // Articles
    'articles.badge': 'Derniers Articles',
    'articles.title': 'Articles',
    'articles.titleHighlight': 'Vedettes',
    'articles.description': 'Analyses expertes, insights et histoires du monde du football.',
    'articles.save': 'Sauvegarder',
    'articles.share': 'Partager',
    'articles.saved': 'Sauvegardé',
    'articles.removed': 'Supprimé',
    'articles.addedToSaved': 'Article ajouté aux favoris',
    'articles.removedFromSaved': 'Article retiré des favoris',
    'articles.copied': 'Copié',
    'articles.linkCopied': 'Lien copié dans le presse-papiers',
    'articles.keywords': 'Mots-clés',
    'articles.shared': 'Partagé',
    'articles.sharedSuccess': 'Article partagé avec succès',
    'articles.shareError': 'Échec du partage',
    'articles.shareErrorDesc': 'Impossible de partager l\'article',
    'articles.translating': 'Traduction en cours...',
    'articles.filters': 'Filtres',
    'articles.clearAll': 'Tout effacer',
    'articles.latest': 'Récent',
    'articles.oldest': 'Ancien',
    'articles.popular': 'Populaire',
    'articles.latestFirst': 'Plus récent',
    'articles.oldestFirst': 'Plus ancien',
    'articles.mostPopular': 'Plus populaire',
    'articles.category': 'Catégorie',
    'articles.author': 'Auteur',
    'articles.showingOf': 'Affichage de {count} sur {total} articles',
    'articles.all': 'Tous',
    'articles.cat.matchAnalysis': 'Analyse de match',
    'articles.cat.transferNews': 'Actualités transferts',
    'articles.cat.playerSpotlight': 'Joueur à l\'honneur',
    'articles.cat.worldCup2026': 'Coupe du Monde 2026',
    'articles.cat.championsLeague': 'Ligue des Champions',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Tactiques',
    'articles.cat.opinion': 'Opinion',
    'articles.cat.didYouKnow': 'Le saviez-vous ?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Business du Football',
    'articles.cat.lifestyle': 'Style de vie',
    'articles.cat.haiti': 'Haïti',
    'ucl.eyebrow': 'Évaluez votre équipe gratuitement',
    'ucl.title': 'Que vaut votre équipe LDC ?',
    'ucl.subtitle': 'Obtenez une note sur 100, voyez ce qui vous coûte des points et trouvez les transferts pour corriger le tir.',
    'ucl.importScreenshot': 'Importer depuis une capture',
    'ucl.buildManually': 'Composer manuellement',
    'ucl.importTitle': 'Importez votre équipe',
    'ucl.importHelp': 'Téléversez une capture de votre équipe Fantasy LDC. Nous lisons les joueurs, votre capitaine et votre banc.',
    'ucl.chooseImage': 'Choisir une image',
    'ucl.buildTitle': 'Composez votre équipe',
    'ucl.formation': 'Formation',
    'ucl.budget': 'Budget',
    'ucl.credit': 'crédit',
    'ucl.optimizeLockedBody': 'Le meilleur onze et le meilleur capitaine parmi vos 15 joueurs.',
    'ucl.captainLockedBody': 'Vos trois meilleurs choix de capitaine, classés par match et par forme.',
    'ucl.chipLockedBody': 'Jouer le Wildcard ou le Limitless cette journée, ou les garder.',
    'ucl.bestPicksLockedBody': 'Les meilleurs joueurs à posséder cette journée, par poste.',
    'ucl.credits': 'crédits',
    'ucl.unlock': 'Débloquer',
    'ucl.signIn': 'Se connecter',
    'ucl.signInToUnlock': 'Créez un compte gratuit et recevez 10 crédits pour débloquer ceci.',
    'ucl.notEnoughCredits': 'Crédits insuffisants.',
    'ucl.topUp': 'Recharger',
    'ucl.topUpPrompt': 'Rechargez pour continuer — 15 crédits pour 0,99 $.',
    'ucl.moreTransfersAvailable': 'autres suggestions de transfert disponibles',
    'ucl.bestPicksNoFixtures': 'Le calendrier n\'est pas encore publié : ce classement se base sur la forme des clubs, pas sur les adversaires.',
    'ucl.bestPicksTitle': 'Analyse du calendrier — meilleurs choix',
    'ucl.bestPicksBody': 'Les joueurs les plus forts à posséder cette journée, classés par match, forme du club et disponibilité.',
    'ucl.cleanSheets': 'clean sheets',
    'ucl.goalsPerGame': 'buts par match',
    'ucl.score.gk': 'Gardiens',
    'ucl.score.def': 'Défenseurs',
    'ucl.score.mid': 'Milieux',
    'ucl.score.fwd': 'Attaquants',
    'ucl.remaining': 'Restant',
    'ucl.overBudget': 'Dépassement de',
    'ucl.pricesPending': 'Prix pas encore publiés',
    'ucl.partialPrices': 'avec prix',
    'ucl.bench': 'Banc',
    'ucl.addPlayer': 'Ajouter',
    'ucl.unknown': 'Inconnu',
    'ucl.pickCaptain': 'Choisissez votre capitaine',
    'ucl.searchPlayer': 'Rechercher un joueur',
    'ucl.loading': 'Chargement...',
    'ucl.noPlayers': 'Aucun joueur trouvé',
    'ucl.playersPicked': 'choisis',
    'ucl.needCaptain': 'Choisissez un capitaine',
    'ucl.rateMyTeam': 'Évaluer mon équipe',
    'ucl.fixManually': 'Corriger manuellement',
    'ucl.couldNotRead': 'Joueurs non reconnus',
    'ucl.reviewNeeded': 'Vérification rapide',
    'ucl.reviewNeededBody': 'Nous n\'avons pas pu lire tous les joueurs. Vérifiez l\'équipe avant l\'évaluation.',
    'ucl.holdOn': 'Un instant',
    'ucl.analyzingTitle': 'Analyse de votre équipe',
    'ucl.analyzing': 'Analyse...',
    'ucl.stage.reading': 'Lecture de votre équipe',
    'ucl.stage.measuring': 'Évaluation des dégâts',
    'ucl.stage.finding': 'Recherche de solutions',
    'ucl.teamRated': 'Votre équipe est notée',
    'ucl.breakdown': 'Détail',
    'ucl.score.captain': 'Choix du capitaine',
    'ucl.score.availability': 'Disponibilité',
    'ucl.score.form': 'Forme',
    'ucl.score.fixtures': 'Calendrier',
    'ucl.score.structure': 'Structure de l\'équipe',
    'ucl.score.diversity': 'Répartition des clubs',
    'ucl.score.value': 'Rapport qualité-prix',
    'ucl.transfers': 'Transferts suggérés',
    'ucl.rateAnother': 'Évaluer une autre équipe',
    'ucl.startOver': 'Recommencer',
    'ucl.error': 'Une erreur est survenue',
    'ucl.viewFixtures': 'Voir le calendrier',
    'ucl.fixturesTitle': 'Calendrier',
    'ucl.matchday': 'Journée',
    'ucl.deadline': 'Date limite',
    'ucl.localTimes': 'Toutes les heures sont affichées dans votre fuseau horaire',
    'ucl.previousMatchday': 'Journée précédente',
    'ucl.nextMatchday': 'Journée suivante',
    'ucl.noFixtures': 'Le calendrier de la phase de ligue n\'a pas encore été publié.',
    'ucl.tbd': 'Date à confirmer',
    'ucl.orPaste': 'ou appuyez sur Ctrl+V pour coller une capture',
    'ucl.optimizeTitle': 'Optimiser mon équipe',
    'ucl.optimizeBody': 'Nous pouvons réorganiser vos 15 joueurs en un onze de départ plus fort :',
    'ucl.optimizeApply': 'Appliquer et réévaluer',
    'ucl.optimizeAlready': 'Votre composition est déjà la meilleure possible avec ces 15 joueurs.',
    'ucl.optimizeAnyway': 'Vérifier à nouveau',
    'ucl.captainTitle': 'Meilleurs choix de capitaine',
    'ucl.chipTitle': 'Conseil sur les jokers',
    'ucl.chipHold': 'Gardez vos jokers',
    'ucl.vs': 'contre',
    'ucl.difficulty': 'difficulté',
    'ucl.showMore': 'Voir plus',
    'articles.cat.uncategorized': 'Non classé',
    'articles.subtitle': 'Les dernières actualités, transferts et analyses du football du monde entier',
    'articles.searchPlaceholder': 'Rechercher des articles...',
    'articles.noResults': 'Aucun article trouvé',
    'articles.tryDifferentSearch': 'Essayez un autre terme ou catégorie',
    'articles.moreStories': 'Plus d\'histoires',
    'articles.backToArticles': 'Retour aux articles',
    'articles.notFound': 'Article non trouvé',
    'articles.views': 'vues',
    'articles.likes': 'J\'aime',
    'articles.similarArticles': 'Articles similaires',
    'articles.loginToLike': 'Connexion requise',
    'articles.loginToLikeDesc': 'Veuillez vous connecter pour aimer les articles',
    'articles.shareSuccess': 'Lien de l\'article copié',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Testez vos connaissances en football avec des défis chronométrés',
    'quiz.noQuizzes': 'Pas encore de quiz disponible',
    'quiz.play': 'Jouer',
    'quiz.startQuiz': 'Commencer le Quiz',
    'quiz.loading': 'Chargement...',
    'quiz.notFound': 'Quiz introuvable',
    'quiz.browseQuizzes': 'Parcourir les Quiz',
    'quiz.minutes': 'minutes',
    'quiz.answers': 'réponses',
    'quiz.answer': 'Réponse',
    'quiz.value': 'Valeur',
    'quiz.typeAnswer': 'Tapez votre réponse...',
    'quiz.giveUp': 'Abandonner',
    'quiz.hint': 'Indice',
    'quiz.loginForHint': 'Connexion requise',
    'quiz.loginForHintDesc': 'Créez un compte pour débloquer les indices',
    'quiz.results': 'Résultats',
    'quiz.timeTaken': 'Temps',
    'quiz.playAgain': 'Rejouer',
    'quiz.share': 'Partager',
    'quiz.shareScore': 'Partager le score',
    'quiz.shareChallenge': 'Tu peux battre mon score ?',
    'quiz.linkCopied': 'Lien copié !',

    // Common
    'common.back': 'Retour',
  },
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.grenadiers': 'Haiti',
    // Grenadiers
    'gren.subtitle': 'Selección nacional de Haití',
    'gren.back': 'Inicio',
    'gren.players': 'jugadores',
    'gren.statLines': 'líneas de estadísticas',
    'gren.callupsWord': 'convocatorias',
    'gren.tabSquad': 'Plantilla',
    'gren.tabStats': 'Estadísticas',
    'gren.tabCallups': 'Convocatorias',
    'gren.posGk': 'Porteros',
    'gren.posDef': 'Defensas',
    'gren.posMid': 'Centrocampistas',
    'gren.posAtt': 'Delanteros',
    'gren.posOther': 'Otros',
    'gren.currentClub': 'Club actual',
    'gren.clubCountry': 'País del club',
    'gren.birth': 'Nacimiento',
    'gren.birthPlace': 'Lugar de nacimiento',
    'gren.marketValue': 'Valor de mercado',
    'gren.status': 'Estado',
    'gren.contract': 'Contrato',
    'gren.agent': 'Agente',
    'gren.injuries': 'Lesiones recientes',
    'gren.career': 'Trayectoria',
    'gren.years': 'años',
    'gren.merchPerso': 'Merch personal',
    'gren.merchClub': 'Merch del club',
    'gren.statsTitle': 'Estadísticas',
    'gren.callupsTitle': 'Convocatorias',
    'gren.thPlayer': 'Jugador',
    'gren.thSeason': 'Temporada',
    'gren.thCompetition': 'Competición',
    'gren.thClub': 'Club/Sel.',
    'gren.thMp': 'PJ',
    'gren.thStarts': 'Tit',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Goles',
    'gren.thAssists': 'A',
    'gren.thYellow': 'TA',
    'gren.thRed': 'TR',
    'gren.thRating': 'Nota',
    'gren.thTournament': 'Torneo',
    'gren.thDate': 'Fecha',
    'gren.thOpponent': 'Rival',
    'gren.thLocation': 'Lugar',
    'gren.thResult': 'Resultado',
    'gren.thPresence': 'Presencia',
    'gren.tournament': 'Torneo',
    'gren.allTournaments': 'Todos los torneos',
    'gren.matches': 'partido(s)',
    'gren.noStats': 'No hay estadísticas disponibles.',
    'gren.noCallups': 'No hay convocatorias disponibles.',
    'gren.present': 'Presente',
    // rebrand app
    'nav.listen': 'Escuchar', 'nav.shop': 'Tienda', 'nav.me': 'Yo',
    'home.askTitle': 'Preguntar a Menlifoot', 'home.askSub': 'Todo sobre el juego — plantillas, historia, táctica.',
    'auth.signin': 'Iniciar sesión', 'auth.signup': 'Registrarse', 'auth.welcome': 'Bienvenido de nuevo', 'auth.createTitle': 'Crea tu cuenta', 'auth.email': 'Correo', 'auth.password': 'Contraseña', 'auth.signinBtn': 'Iniciar sesión', 'auth.signupBtn': 'Crear cuenta', 'auth.checkEmail': 'Revisa tu correo para confirmar tu cuenta.', 'auth.needEmail': 'Ingresa tu correo y contraseña.',
    'home.leadStory': 'Destacado', 'home.latest': 'Recientes', 'home.allAnalysis': 'Todos los análisis',
    'home.podcastNew': 'Podcast · nuevo episodio', 'home.shopDrop': 'Tienda · lanzamiento', 'home.seeAll': 'Ver todo',
    'ask.title': 'Preguntar a Menlifoot', 'ask.sub': 'Entrenado con nuestro archivo · respuestas con fuentes',
    'ask.intro': 'Soy Menlifoot — pregúntame lo que sea del fútbol: plantillas, historia, táctica, los Grenadiers.',
    'ask.placeholder': 'Un partido, una plantilla, un dato…', 'ask.error': 'Vaya, algo salió mal. ¡Inténtalo de nuevo!',
    'ask.p1': '¿Quién es el capitán de Haití?', 'ask.p2': '¿Quién ganó el Mundial 2022?', 'ask.p3': 'Explica la regla del fuera de juego',
    'listen.original': 'Original de Menlifoot', 'listen.title': 'Podcast', 'listen.episodes': 'Episodios', 'listen.watch': 'Ver · entrevistas',
    'shop.nowOpen': 'Abierto', 'shop.store': 'Tienda', 'shop.bag': 'Bolsa', 'shop.limited': 'Limitado', 'shop.size': 'Talla', 'shop.add': 'Añadir',
    'shop.yourBag': 'Tu bolsa', 'shop.subtotal': 'Subtotal', 'shop.shipping': 'Envío', 'shop.total': 'Total',
    'shop.checkout': 'Pagar ahora', 'shop.secure': 'Pago seguro · Stripe', 'shop.empty': 'La bolsa está vacía', 'shop.remove': 'Quitar', 'shop.similar': 'También te puede gustar', 'shop.personalize': 'Personalizar', 'shop.personalizePlaceholder': 'Tu nombre o número', 'shop.personalizeHint': 'Añade un nombre/número y lo imprimiremos en tu artículo.', 'shop.personalized': 'Personalizado', 'shop.favorited': 'Añadido a favoritos', 'shop.linkCopied': '¡Enlace copiado!', 'shop.addedToCart': 'Añadido al carrito', 'shop.viewCart': 'Ver carrito', 'shop.search': 'Buscar', 'shop.all': 'Todas las categorías', 'shop.featured': 'Destacados', 'shop.priceLow': 'Precio: menor a mayor', 'shop.priceHigh': 'Precio: mayor a menor', 'shop.nameAz': 'Nombre: A–Z', 'shop.noResults': 'Sin productos.', 'shop.qty': 'Cantidad',
    'shop.emptyDesc': 'El lanzamiento ya está — gorras, camisetas y la sudadera del podcast.', 'shop.browse': 'Ver la tienda',
    'shop.confirmed': 'Pedido confirmado', 'shop.confirmedDesc': '#MLF-2841 · confirmación enviada. Seguimiento en 24 h.',
    'shop.backStore': 'Volver a la tienda', 'shop.soon': 'Muy pronto', 'shop.shippingTo': 'Envío a', 'shop.firstName': 'Nombre', 'shop.lastName': 'Apellido', 'shop.email': 'Correo', 'shop.phone': 'Teléfono', 'shop.address': 'Dirección', 'shop.address2': 'Apt, suite (opcional)', 'shop.city': 'Ciudad', 'shop.zip': 'Código postal', 'shop.region': 'Estado / Región', 'shop.country': 'País', 'shop.pay': 'Continuar al pago', 'shop.color': 'Color', 'shop.soonDesc': 'La colección Menlifoot está en camino — vuelve pronto.', 'shop.fAll': 'Todo', 'shop.fApparel': 'Ropa', 'shop.fCaps': 'Gorras', 'shop.fAccessories': 'Accesorios',
    'me.saved': 'Guard.', 'me.read': 'Leídos', 'me.streak': 'Racha', 'me.savedArticles': 'Artículos guardados', 'me.orders': 'Historial de pedidos', 'me.noOrders': 'Sin pedidos.', 'me.noSaved': 'Sin artículos guardados.', 'me.memberSince': 'Miembro desde', 'me.liked': 'Artículos que te gustan', 'me.noLiked': 'Sin artículos gustados.', 'me.comments': 'Tus comentarios', 'me.noComments': 'Sin comentarios.', 'me.preferences': 'Preferencias', 'me.activity': 'Actividad', 'me.currentPassword': 'Contraseña actual', 'me.currentPasswordHint': 'Necesaria para cambiar tu correo o contraseña.', 'me.needCurrentPw': 'Ingresa primero tu contraseña actual.', 'me.wrongPw': 'La contraseña actual es incorrecta.', 'me.email': 'Correo', 'me.newPassword': 'Nueva contraseña', 'me.update': 'Actualizar', 'me.emailUpdated': 'Revisa tu nuevo correo para confirmar.', 'me.passwordUpdated': 'Contraseña actualizada.', 'me.pwShort': 'La contraseña debe tener al menos 6 caracteres.', 'order.processing': 'Procesando', 'order.preparing': 'En preparación', 'order.shipped': 'Enviado', 'order.delivered': 'Entregado', 'order.canceled': 'Cancelado', 'order.tracking': 'Seguimiento', 'me.history': 'Historial de lectura',
    'me.notifications': 'Notificaciones', 'me.language': 'Idioma', 'me.signIn': 'Iniciar sesión', 'me.signOut': 'Cerrar sesión',
    'me.notSignedIn': 'No has iniciado sesión', 'me.member': 'Miembro', 'me.plus': 'Menlifoot+',
    'me.plusDesc': 'Lectura sin anuncios, episodios anticipados, 10 % en cada pedido.', 'me.plusPrice': '$4.99 / mes',
    'gren.nationalTeam': 'Selección nacional', 'gren.followTeam': 'Seguir al equipo', 'gren.following': 'Siguiendo', 'gren.lastMatch': 'Último partido',
    'gren.rRecords': 'Récords', 'gren.rResults': 'Resultados', 'gren.rSquad': 'Plantilla', 'gren.rUpcoming': 'Próximos', 'gren.allTimeGoals': 'Goles históricos',
    'gren.mostCaps': 'Más internacionalidades', 'gren.caps': 'int.', 'gren.desc': 'Calendario, convocatorias y un perfil de cada jugador de la selección haitiana — clubes, internacionalidades, goles, valor de mercado.',
    'art.askPiece': 'Preguntar a Menli sobre esto',
    'art.comments': 'Comentarios', 'art.writeComment': 'Escribe un comentario…', 'art.post': 'Publicar', 'art.noComments': 'Sé el primero en comentar.', 'art.linkCopied': '¡Enlace copiado!', 'art.saved': 'Guardado en tus favoritos.', 'art.copyLink': 'Copiar enlace', 'art.shareVia': 'Compartir…',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Artículos',
    'nav.askMenlifoot': 'Preguntar Menlifoot',
    'nav.store': 'Tienda',
    'nav.signIn': 'Iniciar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.editorial': 'Editorial',
    
    // Profile
    'profile.settings': 'Configuración del Perfil',
    'profile.profile': 'Perfil',
    'profile.security': 'Seguridad',
    'profile.avatarHint': 'Haz clic para cambiar el avatar',
    'profile.displayName': 'Nombre',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Cuéntanos sobre ti...',
    'profile.email': 'Correo electrónico',
    'profile.save': 'Guardar Cambios',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.currentPassword': 'Contraseña Actual',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.confirmPassword': 'Confirmar Contraseña',
    'profile.updatePassword': 'Actualizar Contraseña',
    'profile.removeAvatar': 'Eliminar',
    'profile.avatarRemoved': 'Avatar eliminado con éxito',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'Nuevo Episodio Disponible',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Sumérgete en el hermoso juego con análisis de expertos, entrevistas a jugadores y resúmenes de partidos de las ligas más grandes del mundo.',
    'hero.listenNow': 'Escuchar',
    'hero.browseEpisodes': 'Ver Episodios',
    'hero.episodeTitle': 'Adelanto Copa del Mundo 2026',
    'hero.episodeInfo': 'Episodio 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Actualizaciones en Vivo',
    'news.title': 'Últimas',
    'news.titleHighlight': 'Noticias',
    'news.description': 'Mantente actualizado con las últimas noticias del fútbol mundial',
    'news.worldCup': 'Copa del Mundo 2026',
    'news.roadTo2026': 'El Camino a 2026',
    'news.wcDescription': 'Todo lo que necesitas saber sobre la próxima Copa del Mundo FIFA en Estados Unidos, México y Canadá.',
    'news.exploreCoverage': 'Explorar Cobertura',
    'news.latestQualifier': 'Últimos Resultados de Clasificación',
    'news.latestUpdates': 'Últimas Actualizaciones',
    'news.viewAll': 'Ver Todas las Noticias',
    'news.backToNews': 'Volver a Noticias',
    'news.backToHome': 'Volver al Inicio',
    'news.footballNews': 'Fútbol',
    'news.newsTitle': 'Noticias',
    'news.newsDescription': 'Tu fuente de las últimas noticias, fichajes y resultados de fútbol',
    'news.allNews': 'Todas las Noticias',
    'news.transfers': 'Fichajes',
    'news.championsLeague': 'Champions League',
    'news.matches': 'Partidos',
    'news.injuries': 'Lesiones',
    'news.noNews': 'No hay noticias disponibles',
    'news.checkBack': 'Vuelve más tarde para actualizaciones',
    'news.searchPlaceholder': 'Buscar noticias...',
    'news.source': 'Fuente',
    'news.by': 'Por',
    'news.readFull': 'Leer Artículo Completo',
    
    // Merch Section
    'merch.exclusive': 'Colecciones Exclusivas',
    'merch.title': 'Tienda',
    'merch.titleHighlight': 'Oficial',
    'merch.description': 'Muestra tu pasión con productos Menlifoot premium. Ediciones limitadas que no encontrarás en otro lugar.',
    'merch.shopNow': 'Comprar',
    'merch.addToCart': 'Añadir al Carrito',
    'merch.added': 'Añadido al carrito',
    
    // Social Section
    'social.community': 'Únete a la Comunidad',
    'social.title': 'Conéctate',
    'social.titleHighlight': 'Con Nosotros',
    'social.description': 'Sigue nuestro viaje en todas las plataformas y forma parte de la familia Menlifoot.',
    'social.followers': 'seguidores',
    'social.subscribers': 'suscriptores',
    
    // AI Agent
    'ai.title': 'Experto Menlifoot',
    'ai.subtitle': 'Impulsado por Prof Menlifoot',
    'ai.placeholder': 'Pregúntame cualquier cosa sobre fútbol...',
    'ai.greeting': '¡Hola! Soy tu Experto Menlifoot. ¿Tienes preguntas sobre predicciones, estadísticas de jugadores, noticias de fichajes o el Mundial 2026? Hablemos de fútbol.',
    
    // Chat Section
    'chat.poweredBy': 'Impulsado por Prof Menlifoot',
    'chat.askThe': 'Pregunta al',
    'chat.expertName': 'Experto Menlifoot',
    'chat.description': 'Obtén respuestas instantáneas sobre predicciones, estadísticas de jugadores, noticias de fichajes y todo sobre fútbol.',
    'chat.alwaysReady': 'Siempre listo para ayudar',
    'chat.tryAsking': 'Intenta preguntar:',
    
    // Footer
    'footer.tagline': 'Tu compañero definitivo de fútbol. Mantente conectado con el hermoso juego a través de podcasts, noticias y comunidad.',
    'footer.company': 'Empresa',
    'footer.content': 'Contenido',
    'footer.support': 'Soporte',
    'footer.aboutUs': 'Sobre Nosotros',
    'footer.careers': 'Carreras',
    'footer.press': 'Prensa',
    'footer.contact': 'Contacto',
    'footer.podcast': 'Podcast',
    'footer.news': 'Noticias',
    'footer.videos': 'Videos',
    'footer.newsletter': 'Boletín',
    'footer.helpCenter': 'Centro de Ayuda',
    'footer.privacyPolicy': 'Política de Privacidad',
    'footer.termsOfService': 'Términos de Servicio',
    'footer.cookiePolicy': 'Política de Cookies',
    'footer.editorial': 'Editorial',
    'footer.emailPlaceholder': 'Ingresa tu email',
    'footer.rights': 'Todos los derechos reservados.',
    
    // Splash
    'splash.companion': 'El fútbol de otra manera',
    
    // Articles
    'articles.badge': 'Últimos Artículos',
    'articles.title': 'Artículos',
    'articles.titleHighlight': 'Destacados',
    'articles.description': 'Análisis expertos, perspectivas e historias del mundo del fútbol.',
    'articles.save': 'Guardar',
    'articles.share': 'Compartir',
    'articles.saved': 'Guardado',
    'articles.removed': 'Eliminado',
    'articles.addedToSaved': 'Artículo añadido a guardados',
    'articles.removedFromSaved': 'Artículo eliminado de guardados',
    'articles.copied': 'Copiado',
    'articles.linkCopied': 'Enlace copiado al portapapeles',
    'articles.keywords': 'Palabras clave',
    'articles.shared': 'Compartido',
    'articles.sharedSuccess': 'Artículo compartido con éxito',
    'articles.shareError': 'Error al compartir',
    'articles.shareErrorDesc': 'No se pudo compartir el artículo',
    'articles.translating': 'Traduciendo...',
    'articles.filters': 'Filtros',
    'articles.clearAll': 'Borrar todo',
    'articles.latest': 'Reciente',
    'articles.oldest': 'Antiguo',
    'articles.popular': 'Popular',
    'articles.latestFirst': 'Más reciente',
    'articles.oldestFirst': 'Más antiguo',
    'articles.mostPopular': 'Más popular',
    'articles.category': 'Categoría',
    'articles.author': 'Autor',
    'articles.showingOf': 'Mostrando {count} de {total} artículos',
    'articles.all': 'Todos',
    'articles.cat.matchAnalysis': 'Análisis de Partido',
    'articles.cat.transferNews': 'Noticias de Fichajes',
    'articles.cat.playerSpotlight': 'Jugador Destacado',
    'articles.cat.worldCup2026': 'Copa del Mundo 2026',
    'articles.cat.championsLeague': 'Liga de Campeones',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Tácticas',
    'articles.cat.opinion': 'Opinión',
    'articles.cat.didYouKnow': '¿Sabías que?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Negocio del Fútbol',
    'articles.cat.lifestyle': 'Estilo de Vida',
    'articles.cat.haiti': 'Haití',
    'ucl.eyebrow': 'Evalúa tu equipo gratis',
    'ucl.title': '¿Qué tan bueno es tu equipo de la Champions?',
    'ucl.subtitle': 'Consigue una nota sobre 100, descubre qué te cuesta puntos y encuentra los fichajes para arreglarlo.',
    'ucl.importScreenshot': 'Importar desde captura',
    'ucl.buildManually': 'Crear manualmente',
    'ucl.importTitle': 'Importa tu equipo',
    'ucl.importHelp': 'Sube una captura de tu equipo Fantasy de la Champions. Leemos los jugadores, tu capitán y tu banquillo.',
    'ucl.chooseImage': 'Elegir imagen',
    'ucl.buildTitle': 'Crea tu equipo',
    'ucl.formation': 'Formación',
    'ucl.budget': 'Presupuesto',
    'ucl.credit': 'crédito',
    'ucl.optimizeLockedBody': 'El mejor once y el mejor capitán entre los 15 que ya tienes.',
    'ucl.captainLockedBody': 'Tus tres mejores opciones de capitán, por partido y forma.',
    'ucl.chipLockedBody': 'Si jugar el Wildcard o el Limitless esta jornada, o guardarlos.',
    'ucl.bestPicksLockedBody': 'Los mejores jugadores para esta jornada, por posición.',
    'ucl.credits': 'créditos',
    'ucl.unlock': 'Desbloquear',
    'ucl.signIn': 'Iniciar sesión',
    'ucl.signInToUnlock': 'Crea una cuenta gratis y recibe 10 créditos para desbloquear esto.',
    'ucl.notEnoughCredits': 'No tienes suficientes créditos.',
    'ucl.topUp': 'Recargar',
    'ucl.topUpPrompt': 'Recarga para seguir analizando: 15 créditos por 0,99 $.',
    'ucl.moreTransfersAvailable': 'más sugerencias de fichajes disponibles',
    'ucl.bestPicksNoFixtures': 'El calendario aún no se ha publicado, así que esto se ordena por forma del club, no por rival.',
    'ucl.bestPicksTitle': 'Análisis de calendario — mejores fichajes',
    'ucl.bestPicksBody': 'Los jugadores más fuertes para esta jornada, ordenados por partido, forma del club y disponibilidad.',
    'ucl.cleanSheets': 'porterías a cero',
    'ucl.goalsPerGame': 'goles por partido',
    'ucl.score.gk': 'Porteros',
    'ucl.score.def': 'Defensas',
    'ucl.score.mid': 'Centrocampistas',
    'ucl.score.fwd': 'Delanteros',
    'ucl.remaining': 'Restante',
    'ucl.overBudget': 'Te pasas por',
    'ucl.pricesPending': 'Precios aún no publicados',
    'ucl.partialPrices': 'con precio',
    'ucl.bench': 'Banquillo',
    'ucl.addPlayer': 'Añadir',
    'ucl.unknown': 'Desconocido',
    'ucl.pickCaptain': 'Elige tu capitán',
    'ucl.searchPlayer': 'Buscar jugador',
    'ucl.loading': 'Cargando...',
    'ucl.noPlayers': 'No se encontraron jugadores',
    'ucl.playersPicked': 'elegidos',
    'ucl.needCaptain': 'Elige un capitán',
    'ucl.rateMyTeam': 'Evaluar mi equipo',
    'ucl.fixManually': 'Corregir manualmente',
    'ucl.couldNotRead': 'No pudimos leer estos jugadores',
    'ucl.reviewNeeded': 'Revisión rápida',
    'ucl.reviewNeededBody': 'No pudimos leer a todos los jugadores. Revisa el equipo antes de evaluar.',
    'ucl.holdOn': 'Un momento',
    'ucl.analyzingTitle': 'Analizando tu equipo',
    'ucl.analyzing': 'Analizando...',
    'ucl.stage.reading': 'Leyendo tu equipo',
    'ucl.stage.measuring': 'Midiendo el daño',
    'ucl.stage.finding': 'Buscando la solución',
    'ucl.teamRated': 'Tu equipo está evaluado',
    'ucl.breakdown': 'Desglose',
    'ucl.score.captain': 'Elección de capitán',
    'ucl.score.availability': 'Disponibilidad',
    'ucl.score.form': 'Forma',
    'ucl.score.fixtures': 'Calendario',
    'ucl.score.structure': 'Estructura del equipo',
    'ucl.score.diversity': 'Reparto de clubes',
    'ucl.score.value': 'Relación calidad-precio',
    'ucl.transfers': 'Fichajes sugeridos',
    'ucl.rateAnother': 'Evaluar otro equipo',
    'ucl.startOver': 'Empezar de nuevo',
    'ucl.error': 'Algo salió mal',
    'ucl.viewFixtures': 'Ver calendario',
    'ucl.fixturesTitle': 'Calendario',
    'ucl.matchday': 'Jornada',
    'ucl.deadline': 'Fecha límite',
    'ucl.localTimes': 'Todas las horas se muestran en tu hora local',
    'ucl.previousMatchday': 'Jornada anterior',
    'ucl.nextMatchday': 'Jornada siguiente',
    'ucl.noFixtures': 'El calendario de la fase de liga todavía no se ha publicado.',
    'ucl.tbd': 'Fecha por confirmar',
    'ucl.orPaste': 'o pulsa Ctrl+V para pegar una captura',
    'ucl.optimizeTitle': 'Optimizar mi equipo',
    'ucl.optimizeBody': 'Podemos reorganizar tus 15 jugadores en un once inicial más fuerte:',
    'ucl.optimizeApply': 'Aplicar y volver a puntuar',
    'ucl.optimizeAlready': 'Tu alineación ya es la mejor posible con estos 15 jugadores.',
    'ucl.optimizeAnyway': 'Volver a comprobar',
    'ucl.captainTitle': 'Mejores opciones de capitán',
    'ucl.chipTitle': 'Consejo de comodines',
    'ucl.chipHold': 'Guarda tus comodines',
    'ucl.vs': 'contra',
    'ucl.difficulty': 'dificultad',
    'ucl.showMore': 'Ver más',
    'articles.cat.uncategorized': 'Sin Categoría',
    'articles.subtitle': 'Las últimas noticias, fichajes y análisis del fútbol mundial',
    'articles.searchPlaceholder': 'Buscar artículos...',
    'articles.noResults': 'No se encontraron artículos',
    'articles.tryDifferentSearch': 'Prueba con otro término o categoría',
    'articles.moreStories': 'Más historias',
    'articles.backToArticles': 'Volver a artículos',
    'articles.notFound': 'Artículo no encontrado',
    'articles.views': 'vistas',
    'articles.likes': 'Me gusta',
    'articles.similarArticles': 'Artículos similares',
    'articles.loginToLike': 'Inicio de sesión requerido',
    'articles.loginToLikeDesc': 'Por favor inicia sesión para dar me gusta',
    'articles.shareSuccess': 'Enlace del artículo copiado',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Pon a prueba tus conocimientos de fútbol con desafíos cronometrados',
    'quiz.noQuizzes': 'Aún no hay quizzes disponibles',
    'quiz.play': 'Jugar',
    'quiz.startQuiz': 'Comenzar Quiz',
    'quiz.loading': 'Cargando...',
    'quiz.notFound': 'Quiz no encontrado',
    'quiz.browseQuizzes': 'Ver Quizzes',
    'quiz.minutes': 'minutos',
    'quiz.answers': 'respuestas',
    'quiz.answer': 'Respuesta',
    'quiz.value': 'Valor',
    'quiz.typeAnswer': 'Escribe tu respuesta...',
    'quiz.giveUp': 'Rendirse',
    'quiz.hint': 'Pista',
    'quiz.loginForHint': 'Inicio de sesión requerido',
    'quiz.loginForHintDesc': 'Crea una cuenta para desbloquear pistas',
    'quiz.results': 'Resultados',
    'quiz.timeTaken': 'Tiempo',
    'quiz.playAgain': 'Jugar de Nuevo',
    'quiz.share': 'Compartir',
    'quiz.shareScore': 'Compartir Puntuación',
    'quiz.shareChallenge': '¿Puedes superar mi puntuación?',
    'quiz.linkCopied': '¡Enlace copiado!',

    // Common
    'common.back': 'Volver',
  },
  ht: {
    // Navbar
    'nav.home': 'Lakay',
    'nav.grenadiers': 'Haiti',
    // Grenadiers
    'gren.subtitle': 'Seleksyon nasyonal Ayiti',
    'gren.back': 'Lakay',
    'gren.players': 'jwè',
    'gren.statLines': 'liy estatistik',
    'gren.callupsWord': 'konvokasyon',
    'gren.tabSquad': 'Efektif',
    'gren.tabStats': 'Estatistik',
    'gren.tabCallups': 'Konvokasyon',
    'gren.posGk': 'Gadyen',
    'gren.posDef': 'Defansè',
    'gren.posMid': 'Milye',
    'gren.posAtt': 'Atakan',
    'gren.posOther': 'Lòt',
    'gren.currentClub': 'Klib aktyèl',
    'gren.clubCountry': 'Peyi klib la',
    'gren.birth': 'Nesans',
    'gren.birthPlace': 'Kote li fèt',
    'gren.marketValue': 'Valè sou mache',
    'gren.status': 'Estati',
    'gren.contract': 'Kontra',
    'gren.agent': 'Ajan',
    'gren.injuries': 'Blesi resan',
    'gren.career': 'Parkou',
    'gren.years': 'lane',
    'gren.merchPerso': 'Machandiz pèsonèl',
    'gren.merchClub': 'Machandiz klib',
    'gren.statsTitle': 'Estatistik',
    'gren.callupsTitle': 'Konvokasyon',
    'gren.thPlayer': 'Jwè',
    'gren.thSeason': 'Sezon',
    'gren.thCompetition': 'Konpetisyon',
    'gren.thClub': 'Klib/Sel.',
    'gren.thMp': 'MJ',
    'gren.thStarts': 'Tit',
    'gren.thMin': 'Min',
    'gren.thGoals': 'Gòl',
    'gren.thAssists': 'PD',
    'gren.thYellow': 'KJ',
    'gren.thRed': 'KR',
    'gren.thRating': 'Nòt',
    'gren.thTournament': 'Tounwa',
    'gren.thDate': 'Dat',
    'gren.thOpponent': 'Advèsè',
    'gren.thLocation': 'Kote',
    'gren.thResult': 'Rezilta',
    'gren.thPresence': 'Prezans',
    'gren.tournament': 'Tounwa',
    'gren.allTournaments': 'Tout tounwa yo',
    'gren.matches': 'match',
    'gren.noStats': 'Pa gen estatistik disponib.',
    'gren.noCallups': 'Pa gen konvokasyon disponib.',
    'gren.present': 'Prezan',
    // rebrand app
    'nav.listen': 'Koute', 'nav.shop': 'Boutik', 'nav.me': 'Mwen',
    'home.askTitle': 'Mande Menlifoot', 'home.askSub': 'Nenpòt bagay sou match la — ekip, istwa, taktik.',
    'auth.signin': 'Konekte', 'auth.signup': 'Enskri', 'auth.welcome': 'Byenvini ankò', 'auth.createTitle': 'Kreye kont ou', 'auth.email': 'Imèl', 'auth.password': 'Modpas', 'auth.signinBtn': 'Konekte', 'auth.signupBtn': 'Kreye kont', 'auth.checkEmail': 'Tcheke imèl ou pou konfime kont ou.', 'auth.needEmail': 'Antre imèl ak modpas ou.',
    'home.leadStory': 'Gwo istwa', 'home.latest': 'Dènye yo', 'home.allAnalysis': 'Tout analiz',
    'home.podcastNew': 'Podcast · nouvo epizòd', 'home.shopDrop': 'Boutik · lansman', 'home.seeAll': 'Wè tout',
    'ask.title': 'Mande Menlifoot', 'ask.sub': 'Antrene sou achiv nou · repons ak sous',
    'ask.intro': 'Se mwen Menlifoot — mande m nenpòt bagay sou foutbòl: ekip, istwa, taktik, Grenadye yo.',
    'ask.placeholder': 'Yon match, yon ekip, yon estatistik…', 'ask.error': 'Padon, gen yon pwoblèm. Eseye ankò!',
    'ask.p1': 'Kiyès ki kapitèn Ayiti?', 'ask.p2': 'Kiyès ki genyen Mondyal 2022?', 'ask.p3': 'Eksplike règ hòsjè a',
    'listen.original': 'Orijinal Menlifoot', 'listen.title': 'Podcast', 'listen.episodes': 'Epizòd', 'listen.watch': 'Gade · entèvyou',
    'shop.nowOpen': 'Louvri', 'shop.store': 'Boutik', 'shop.bag': 'Sak', 'shop.limited': 'Limite', 'shop.size': 'Gwosè', 'shop.add': 'Ajoute',
    'shop.yourBag': 'Sak ou', 'shop.subtotal': 'Sou-total', 'shop.shipping': 'Livrezon', 'shop.total': 'Total',
    'shop.checkout': 'Peye kounye a', 'shop.secure': 'Peman sekirize · Stripe', 'shop.empty': 'Pa gen anyen nan sak la', 'shop.remove': 'Retire', 'shop.similar': 'Ou ka renmen tou', 'shop.personalize': 'Pèsonalize li', 'shop.personalizePlaceholder': 'Non ou oswa nimewo', 'shop.personalizeHint': 'Mete yon non/nimewo epi n ap enprime l sou atik ou.', 'shop.personalized': 'Pèsonalize', 'shop.favorited': 'Ajoute nan favori', 'shop.linkCopied': 'Lyen kopye!', 'shop.addedToCart': 'Ajoute nan panye', 'shop.viewCart': 'Wè panye', 'shop.search': 'Chèche pwodwi', 'shop.all': 'Tout kategori', 'shop.featured': 'Chwazi', 'shop.priceLow': 'Pri: piti a gwo', 'shop.priceHigh': 'Pri: gwo a piti', 'shop.nameAz': 'Non: A–Z', 'shop.noResults': 'Pa gen pwodwi.', 'shop.qty': 'Kantite',
    'shop.emptyDesc': 'Lansman an la — kaskèt, chemiz ak sweatshirt podcast la.', 'shop.browse': 'Gade boutik la',
    'shop.confirmed': 'Kòmand konfime', 'shop.confirmedDesc': '#MLF-2841 · konfimasyon voye. W ap jwenn swivi nan 24 èdtan.',
    'shop.backStore': 'Retounen boutik', 'shop.soon': 'Talè konsa', 'shop.shippingTo': 'Livrezon', 'shop.firstName': 'Prenon', 'shop.lastName': 'Non', 'shop.email': 'Imèl', 'shop.phone': 'Telefòn', 'shop.address': 'Adrès', 'shop.address2': 'Apt, suite (opsyonèl)', 'shop.city': 'Vil', 'shop.zip': 'Kòd postal', 'shop.region': 'Eta / Rejyon', 'shop.country': 'Peyi', 'shop.pay': 'Kontinye nan peman', 'shop.color': 'Koulè', 'shop.soonDesc': 'Koleksyon Menlifoot la ap vini — retounen talè.', 'shop.fAll': 'Tout', 'shop.fApparel': 'Rad', 'shop.fCaps': 'Kaskèt', 'shop.fAccessories': 'Akseswa',
    'me.saved': 'Sere', 'me.read': 'Li', 'me.streak': 'Seri', 'me.savedArticles': 'Atik sere', 'me.orders': 'Istorik kòmand', 'me.noOrders': 'Pa gen kòmand.', 'me.noSaved': 'Pa gen atik sere.', 'me.memberSince': 'Manm depi', 'me.liked': 'Atik ou renmen', 'me.noLiked': 'Pa gen atik ou renmen.', 'me.comments': 'Kòmantè ou yo', 'me.noComments': 'Pa gen kòmantè.', 'me.preferences': 'Preferans', 'me.activity': 'Aktivite', 'me.currentPassword': 'Modpas aktyèl', 'me.currentPasswordHint': 'Obligatwa pou chanje imèl oswa modpas ou.', 'me.needCurrentPw': 'Antre modpas aktyèl ou anvan.', 'me.wrongPw': 'Modpas aktyèl la pa kòrèk.', 'me.email': 'Imèl', 'me.newPassword': 'Nouvo modpas', 'me.update': 'Mete ajou', 'me.emailUpdated': 'Tcheke nouvo imèl ou pou konfime.', 'me.passwordUpdated': 'Modpas mete ajou.', 'me.pwShort': 'Modpas la dwe gen omwen 6 karaktè.', 'order.processing': 'Ap trete', 'order.preparing': 'Ap prepare', 'order.shipped': 'Ekspedye', 'order.delivered': 'Livre', 'order.canceled': 'Anile', 'order.tracking': 'Swivi', 'me.history': 'Istorik lekti',
    'me.notifications': 'Notifikasyon', 'me.language': 'Lang', 'me.signIn': 'Konekte', 'me.signOut': 'Dekonekte',
    'me.notSignedIn': 'Ou pa konekte', 'me.member': 'Manm', 'me.plus': 'Menlifoot+',
    'me.plusDesc': 'Lekti san reklam, epizòd davans, 10% sou chak kòmand.', 'me.plusPrice': '$4.99 / mwa',
    'gren.nationalTeam': 'Seleksyon nasyonal', 'gren.followTeam': 'Swiv ekip la', 'gren.following': 'Ap swiv', 'gren.lastMatch': 'Dènye match',
    'gren.rRecords': 'Rekò', 'gren.rResults': 'Rezilta', 'gren.rSquad': 'Efektif', 'gren.rUpcoming': 'Kap vini', 'gren.allTimeGoals': 'Gòl tout tan',
    'gren.mostCaps': 'Plis seleksyon', 'gren.caps': 'sel.', 'gren.desc': 'Kalandriye, konvokasyon ak yon pwofil pou chak jwè nan seleksyon ayisyen an — klib, seleksyon, gòl, valè sou mache.',
    'art.askPiece': 'Mande Menli sou atik sa a',
    'art.comments': 'Kòmantè', 'art.writeComment': 'Ekri yon kòmantè…', 'art.post': 'Pibliye', 'art.noComments': 'Se ou k ap premye komante.', 'art.linkCopied': 'Lyen kopye!', 'art.saved': 'Sere nan makè ou yo.', 'art.copyLink': 'Kopye lyen', 'art.shareVia': 'Pataje…',
    'nav.podcast': 'Podcast',
    'nav.articles': 'Atik yo',
    'nav.askMenlifoot': 'Mande Menlifoot',
    'nav.store': 'Boutik',
    'nav.signIn': 'Konekte',
    'nav.login': 'Konekte',
    'nav.logout': 'Dekonekte',
    'nav.editorial': 'Editoryal',
    
    // Profile
    'profile.settings': 'Paramèt Pwofil',
    'profile.profile': 'Pwofil',
    'profile.security': 'Sekirite',
    'profile.avatarHint': 'Klike pou chanje avatar',
    'profile.displayName': 'Non Afichaj',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Di nou sou ou...',
    'profile.email': 'Imèl',
    'profile.save': 'Anrejistre Chanjman',
    'profile.changePassword': 'Chanje Modpas',
    'profile.currentPassword': 'Modpas Aktyèl',
    'profile.newPassword': 'Nouvo Modpas',
    'profile.confirmPassword': 'Konfime Modpas',
    'profile.updatePassword': 'Mete Modpas Ajou',
    'profile.removeAvatar': 'Retire',
    'profile.avatarRemoved': 'Avatar retire avèk siksè',
    
    // Hero/Podcast Section
    'hero.newEpisode': 'Nouvo Epizòd Disponib',
    'hero.podcast': 'Podcast',
    'hero.podcastDescription': 'Plonje nan bèl jwèt la ak analiz ekspè, entèvyou jwè, ak rezime match nan pi gwo lig nan mond lan.',
    'hero.listenNow': 'Koute Kounye a',
    'hero.browseEpisodes': 'Wè Epizòd yo',
    'hero.episodeTitle': 'Apèsi Koup di Mond 2026',
    'hero.episodeInfo': 'Epizòd 47 • 45 min',
    
    // News Section
    'news.liveUpdates': 'Mizajou an Dirèk',
    'news.title': 'Dènye',
    'news.titleHighlight': 'Nouvèl',
    'news.description': 'Rete enfòme ak dènye nouvèl foutbòl nan mond lan',
    'news.worldCup': 'Koup di Mond 2026',
    'news.roadTo2026': 'Wout pou 2026',
    'news.wcDescription': 'Tout sa ou bezwen konnen sou pwochen Koup di Mond FIFA nan Etazini, Meksik ak Kanada.',
    'news.exploreCoverage': 'Eksplore Kouvèti',
    'news.latestQualifier': 'Dènye Rezilta Kalifikasyon',
    'news.latestUpdates': 'Dènye Mizajou',
    'news.viewAll': 'Wè Tout Nouvèl',
    'news.backToNews': 'Retounen nan Nouvèl',
    'news.backToHome': 'Retounen Lakay',
    'news.footballNews': 'Foutbòl',
    'news.newsTitle': 'Nouvèl',
    'news.newsDescription': 'Sous ou pou dènye nouvèl foutbòl, transfè ak rezilta match',
    'news.allNews': 'Tout Nouvèl',
    'news.transfers': 'Transfè',
    'news.championsLeague': 'Lig Chanpyon',
    'news.matches': 'Match',
    'news.injuries': 'Blesi',
    'news.noNews': 'Pa gen nouvèl disponib',
    'news.checkBack': 'Retounen pita pou mizajou',
    'news.searchPlaceholder': 'Chèche nouvèl...',
    'news.source': 'Sous',
    'news.by': 'Pa',
    'news.readFull': 'Li Atik Konplè',
    
    // Merch Section
    'merch.exclusive': 'Koleksyon Eksklizif',
    'merch.title': 'Boutik',
    'merch.titleHighlight': 'Ofisyèl',
    'merch.description': 'Montre pasyon ou ak pwodui Menlifoot premyòm. Edisyon limite ou pap jwenn okenn lòt kote.',
    'merch.shopNow': 'Achte',
    'merch.addToCart': 'Mete nan Panye',
    'merch.added': 'Ajoute nan panye',
    
    // Social Section
    'social.community': 'Rejwenn Kominote a',
    'social.title': 'Konekte',
    'social.titleHighlight': 'Avèk Nou',
    'social.description': 'Swiv vwayaj nou sou tout platfòm yo epi vin fè pati fanmi Menlifoot la.',
    'social.followers': 'moun kap swiv',
    'social.subscribers': 'abòne',
    
    // AI Agent
    'ai.title': 'Ekspè Menlifoot',
    'ai.subtitle': 'Pouvwa pa Prof Menlifoot',
    'ai.placeholder': 'Mande m nenpòt bagay sou foutbòl...',
    'ai.greeting': 'Sak pase! Mwen se Ekspè Menlifoot ou. Ou gen kesyon sou prediksyon match, estatistik jwè, nouvèl transfè, oswa Koup di Mond 2026? Ann pale foutbòl.',
    
    // Chat Section
    'chat.poweredBy': 'Pouvwa pa Prof Menlifoot',
    'chat.askThe': 'Mande',
    'chat.expertName': 'Ekspè Menlifoot la',
    'chat.description': 'Jwenn repons imedyat sou prediksyon match, estatistik jwè, nouvèl transfè, ak tout bagay sou foutbòl.',
    'chat.alwaysReady': 'Toujou pare pou ede',
    'chat.tryAsking': 'Eseye mande:',
    
    // Footer
    'footer.tagline': 'Patnè foutbòl final ou. Rete konekte ak bèl jwèt la atravè podcast, nouvèl, ak kominote.',
    'footer.company': 'Konpayi',
    'footer.content': 'Kontni',
    'footer.support': 'Sipò',
    'footer.aboutUs': 'Konsènan Nou',
    'footer.careers': 'Karyè',
    'footer.press': 'Laprès',
    'footer.contact': 'Kontakte',
    'footer.podcast': 'Podcast',
    'footer.news': 'Nouvèl',
    'footer.videos': 'Videyo',
    'footer.newsletter': 'Bilten',
    'footer.helpCenter': 'Sant Èd',
    'footer.privacyPolicy': 'Règ Konfidansyalite',
    'footer.termsOfService': 'Kondisyon Sèvis',
    'footer.cookiePolicy': 'Règ Cookie',
    'footer.editorial': 'Editoryal',
    'footer.emailPlaceholder': 'Antre imèl ou',
    'footer.rights': 'Tout dwa rezève.',
    
    // Splash
    'splash.companion': 'Foutbòl yon lòt jan',
    
    // Articles
    'articles.badge': 'Dènye Atik yo',
    'articles.title': 'Atik',
    'articles.titleHighlight': 'Vedèt',
    'articles.description': 'Analiz ekspè, pèspektiv ak istwa nan mond foutbòl la.',
    'articles.save': 'Sere',
    'articles.share': 'Pataje',
    'articles.saved': 'Sere',
    'articles.removed': 'Retire',
    'articles.addedToSaved': 'Atik ajoute nan sere yo',
    'articles.removedFromSaved': 'Atik retire nan sere yo',
    'articles.copied': 'Kopye',
    'articles.linkCopied': 'Lyen kopye nan pres-papye',
    'articles.keywords': 'Mo Kle',
    'articles.shared': 'Pataje',
    'articles.sharedSuccess': 'Atik pataje avèk siksè',
    'articles.shareError': 'Echèk pataj',
    'articles.shareErrorDesc': 'Pa kapab pataje atik la',
    'articles.translating': 'Ap tradui...',
    'articles.filters': 'Filtè',
    'articles.clearAll': 'Efase tout',
    'articles.latest': 'Dènye',
    'articles.oldest': 'Pi ansyen',
    'articles.popular': 'Popilè',
    'articles.latestFirst': 'Pi resan an premye',
    'articles.oldestFirst': 'Pi ansyen an premye',
    'articles.mostPopular': 'Pi popilè',
    'articles.category': 'Kategori',
    'articles.author': 'Otè',
    'articles.showingOf': 'Montre {count} sou {total} atik',
    'articles.all': 'Tout',
    'articles.cat.matchAnalysis': 'Analiz Match',
    'articles.cat.transferNews': 'Nouvèl Transfè',
    'articles.cat.playerSpotlight': 'Jwè an Vedèt',
    'articles.cat.worldCup2026': 'Koup di Mond 2026',
    'articles.cat.championsLeague': 'Lig Chanpyon',
    'articles.cat.premierLeague': 'Premier League',
    'articles.cat.laLiga': 'La Liga',
    'articles.cat.serieA': 'Serie A',
    'articles.cat.bundesliga': 'Bundesliga',
    'articles.cat.mls': 'MLS',
    'articles.cat.tactics': 'Taktik',
    'articles.cat.opinion': 'Opinyon',
    'articles.cat.didYouKnow': 'Èske ou te konnen?',
    'articles.cat.flashback': 'Flashback',
    'articles.cat.footballBusiness': 'Biznis Foutbòl',
    'articles.cat.lifestyle': 'Stil Lavi',
    'articles.cat.haiti': 'Ayiti',
    'ucl.eyebrow': 'Evalye ekip ou gratis',
    'ucl.title': 'Konbyen ekip ou a vo?',
    'ucl.subtitle': 'Jwenn yon nòt sou 100, wè sa k ap koute w pwen, epi jwenn transfè pou ranje l.',
    'ucl.importScreenshot': 'Enpòte depi yon foto ekran',
    'ucl.buildManually': 'Bati manyèlman',
    'ucl.importTitle': 'Enpòte ekip ou',
    'ucl.importHelp': 'Voye yon foto ekran ekip fantasy ou. Nou li jwè yo, kapitèn ou ak ban ou.',
    'ucl.chooseImage': 'Chwazi yon imaj',
    'ucl.buildTitle': 'Bati ekip ou',
    'ucl.formation': 'Fòmasyon',
    'ucl.budget': 'Bidjè',
    'ucl.credit': 'kredi',
    'ucl.optimizeLockedBody': 'Pi bon onz la ak pi bon kapitèn nan 15 jwè ou deja genyen.',
    'ucl.captainLockedBody': 'Twa pi bon chwa kapitèn ou, klase selon match la ak fòm.',
    'ucl.chipLockedBody': 'Èske pou jwe Wildcard oswa Limitless jounen sa a, oswa kenbe yo.',
    'ucl.bestPicksLockedBody': 'Pi bon jwè pou ou genyen jounen sa a, selon pozisyon.',
    'ucl.credits': 'kredi',
    'ucl.unlock': 'Debloke',
    'ucl.signIn': 'Konekte',
    'ucl.signInToUnlock': 'Kreye yon kont gratis epi jwenn 10 kredi pou debloke sa a.',
    'ucl.notEnoughCredits': 'Ou pa gen ase kredi.',
    'ucl.topUp': 'Rechaje',
    'ucl.topUpPrompt': 'Rechaje pou kontinye analize — 15 kredi pou 0,99 $.',
    'ucl.moreTransfersAvailable': 'lòt sijesyon transfè ki disponib',
    'ucl.bestPicksNoFixtures': 'Yo poko pibliye kalandriye a, donk klasman sa a baze sou fòm klib yo, pa sou advèsè yo.',
    'ucl.bestPicksTitle': 'Analiz kalandriye — pi bon chwa',
    'ucl.bestPicksBody': 'Jwè ki pi solid pou ou genyen jounen sa a, klase selon match la, fòm klib la ak disponibilite.',
    'ucl.cleanSheets': 'match san gòl',
    'ucl.goalsPerGame': 'gòl pa match',
    'ucl.score.gk': 'Gadyen',
    'ucl.score.def': 'Defansè',
    'ucl.score.mid': 'Milye',
    'ucl.score.fwd': 'Atakan',
    'ucl.remaining': 'Rete',
    'ucl.overBudget': 'Ou depase ak',
    'ucl.pricesPending': 'Yo poko pibliye pri yo',
    'ucl.partialPrices': 'ki gen pri',
    'ucl.bench': 'Ban',
    'ucl.addPlayer': 'Ajoute',
    'ucl.unknown': 'Enkoni',
    'ucl.pickCaptain': 'Chwazi kapitèn ou',
    'ucl.searchPlayer': 'Chèche yon jwè',
    'ucl.loading': 'Ap chaje...',
    'ucl.noPlayers': 'Nou pa jwenn okenn jwè',
    'ucl.playersPicked': 'chwazi',
    'ucl.needCaptain': 'Chwazi yon kapitèn',
    'ucl.rateMyTeam': 'Evalye ekip mwen',
    'ucl.fixManually': 'Ranje l manyèlman',
    'ucl.couldNotRead': 'Nou pa t ka li jwè sa yo',
    'ucl.reviewNeeded': 'Fè yon ti tcheke',
    'ucl.reviewNeededBody': 'Nou pa t ka li tout jwè yo. Tcheke ekip la anvan ou evalye.',
    'ucl.holdOn': 'Tann yon ti moman',
    'ucl.analyzingTitle': 'N ap analize ekip ou',
    'ucl.analyzing': 'N ap analize...',
    'ucl.stage.reading': 'N ap li ekip ou',
    'ucl.stage.measuring': 'N ap mezire dega yo',
    'ucl.stage.finding': 'N ap chèche solisyon',
    'ucl.teamRated': 'Ekip ou gen nòt li',
    'ucl.breakdown': 'Detay',
    'ucl.score.captain': 'Chwa kapitèn',
    'ucl.score.availability': 'Disponibilite',
    'ucl.score.form': 'Fòm',
    'ucl.score.fixtures': 'Kalandriye',
    'ucl.score.structure': 'Estrikti ekip la',
    'ucl.score.diversity': 'Repartisyon klib yo',
    'ucl.score.value': 'Valè',
    'ucl.transfers': 'Transfè nou sijere',
    'ucl.rateAnother': 'Evalye yon lòt ekip',
    'ucl.startOver': 'Rekòmanse',
    'ucl.error': 'Gen yon bagay ki pa mache',
    'ucl.viewFixtures': 'Gade kalandriye a',
    'ucl.fixturesTitle': 'Kalandriye',
    'ucl.matchday': 'Jounen match',
    'ucl.deadline': 'Dat limit',
    'ucl.localTimes': 'Tout lè yo parèt nan lè lokal ou',
    'ucl.previousMatchday': 'Jounen anvan an',
    'ucl.nextMatchday': 'Jounen apre a',
    'ucl.noFixtures': 'Yo poko pibliye kalandriye faz lig la.',
    'ucl.tbd': 'Dat la poko konfime',
    'ucl.orPaste': 'oswa peze Ctrl+V pou kole yon foto ekran',
    'ucl.optimizeTitle': 'Optimize ekip mwen',
    'ucl.optimizeBody': 'Nou ka reòganize 15 jwè ou yo pou fè yon onz depa ki pi solid:',
    'ucl.optimizeApply': 'Aplike epi re-evalye',
    'ucl.optimizeAlready': 'Konpozisyon ou deja pi bon aranjman ou ka fè ak 15 jwè sa yo.',
    'ucl.optimizeAnyway': 'Tcheke ankò',
    'ucl.captainTitle': 'Pi bon chwa kapitèn',
    'ucl.chipTitle': 'Konsèy sou jokè yo',
    'ucl.chipHold': 'Kenbe jokè ou yo',
    'ucl.vs': 'kont',
    'ucl.difficulty': 'difikilte',
    'ucl.showMore': 'Gade plis',
    'articles.cat.uncategorized': 'San Kategori',
    'articles.subtitle': 'Dènye nouvèl foutbòl, transfè ak analiz nan mond antye',
    'articles.searchPlaceholder': 'Chèche atik...',
    'articles.noResults': 'Pa jwenn okenn atik',
    'articles.tryDifferentSearch': 'Eseye yon lòt tèm oswa kategori',
    'articles.moreStories': 'Plis istwa',
    'articles.backToArticles': 'Retounen nan atik yo',
    'articles.notFound': 'Atik pa jwenn',
    'articles.views': 'vi',
    'articles.likes': 'Renmen',
    'articles.similarArticles': 'Atik menm jan',
    'articles.loginToLike': 'Koneksyon obligatwa',
    'articles.loginToLikeDesc': 'Tanpri konekte pou renmen atik yo',
    'articles.shareSuccess': 'Lyen atik kopye',
    
    // Quiz
    'nav.quiz': 'Quiz',
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Teste konesans foutbòl ou ak defi kronometre',
    'quiz.noQuizzes': 'Pa gen quiz disponib ankò',
    'quiz.play': 'Jwe',
    'quiz.startQuiz': 'Kòmanse Quiz',
    'quiz.loading': 'Ap chaje...',
    'quiz.notFound': 'Quiz pa jwenn',
    'quiz.browseQuizzes': 'Wè Quiz yo',
    'quiz.minutes': 'minit',
    'quiz.answers': 'repons',
    'quiz.answer': 'Repons',
    'quiz.value': 'Valè',
    'quiz.typeAnswer': 'Tape repons ou...',
    'quiz.giveUp': 'Abandone',
    'quiz.hint': 'Endis',
    'quiz.loginForHint': 'Koneksyon obligatwa',
    'quiz.loginForHintDesc': 'Kreye yon kont pou debloke endis',
    'quiz.results': 'Rezilta',
    'quiz.timeTaken': 'Tan',
    'quiz.playAgain': 'Jwe Ankò',
    'quiz.share': 'Pataje',
    'quiz.shareScore': 'Pataje Rezilta',
    'quiz.shareChallenge': 'Èske ou ka bat rezilta mwen an?',
    'quiz.linkCopied': 'Lyen kopye!',

    // Common
    'common.back': 'Retounen',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('menlifoot-language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('menlifoot-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  fr: 'Français',
  es: 'Español',
  ht: 'Kreyòl',
};
